// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public static partial class LucideRegistry
{
    private static IReadOnlyList<LucideIconModel>? _securityIcons;
    public static IReadOnlyList<LucideIconModel> SecurityIcons => _securityIcons ??= CreateSecurityIcons();

    private static LucideIconModel[] CreateSecurityIcons()
    {
        return new LucideIconModel[]
        {
            new("bomb", "Bomb", new string[] { "fatal", "error", "crash", "blockbuster", "mine", "explosion", "explode", "explosive" }, new string[] { "Security", "Tools" }, "<circle cx=\"11\" cy=\"13\" r=\"9\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14.35 4.65 16.3 2.7a2.41 2.41 0 0 1 3.4 0l1.6 1.6a2.4 2.4 0 0 1 0 3.4l-1.95 1.95\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m22 2-1.5 1.5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("brick-wall-fire", "BrickWallFire", new string[] { "firewall", "security", "bricks", "mortar", "cement", "materials", "construction", "builder", "labourer", "quantity surveyor", "blocks", "stone", "campfire", "camping", "wilderness", "outdoors", "lit", "warmth", "wood", "twigs", "sticks" }, new string[] { "Security", "Home", "Connectivity" }, "<path d=\"M16 3v2.107\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 9c1 3 2.5 3.5 3.5 4.5A5 5 0 0 1 22 17a5 5 0 0 1-10 0c0-.3 0-.6.1-.9a2 2 0 1 0 3.3-2C13 11.5 16 9 17 9\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 8.274V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h3.938\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 15h5.253\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 9h8.228\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 15v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 3v6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("brick-wall-shield", "BrickWallShield", new string[] { "firewall", "security", "bricks", "mortar", "cement", "materials", "construction", "builder", "labourer", "quantity surveyor", "blocks", "stone", "cybersecurity", "secure", "safety", "protection", "guardian", "armored", "armoured", "defense", "defence", "defender", "block", "threat", "prevention", "antivirus", "vigilance", "vigilant", "detection", "scan", "find", "strength", "strong", "tough", "invincible", "invincibility", "invulnerable", "undamaged", "audit", "admin", "verification", "crest", "bravery", "knight", "foot soldier", "infantry", "trooper", "pawn", "battle", "war", "military", "army", "cadet", "scout" }, new string[] { "Security", "Home", "Connectivity" }, "<path d=\"M12 9v1.258\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 3v5.46\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 9.118V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h5.75\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 17.5c0 2.499-1.75 3.749-3.83 4.474a.5.5 0 0 1-.335-.005c-2.085-.72-3.835-1.97-3.835-4.47V14a.5.5 0 0 1 .5-.499c1 0 2.25-.6 3.12-1.36a.6.6 0 0 1 .76-.001c.875.765 2.12 1.36 3.12 1.36a.5.5 0 0 1 .5.5z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 15h7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 9h12.142\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 15v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 3v6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("cctv", "Cctv", new string[] { "camera", "surveillance", "recording", "film", "videotape", "crime", "watching" }, new string[] { "Security", "Devices", "Communication", "Connectivity", "Photography" }, "<path d=\"M16.75 12h3.632a1 1 0 0 1 .894 1.447l-2.034 4.069a1 1 0 0 1-1.708.134l-2.124-2.97\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.106 9.053a1 1 0 0 1 .447 1.341l-3.106 6.211a1 1 0 0 1-1.342.447L3.61 12.3a2.92 2.92 0 0 1-1.3-3.91L3.69 5.6a2.92 2.92 0 0 1 3.92-1.3z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 19h3.76a2 2 0 0 0 1.8-1.1L9 15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 21v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 9h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("cctv-off", "CctvOff", new string[] { "camera", "surveillance", "recording", "film", "videotape", "crime", "watching" }, new string[] { "Security", "Devices", "Communication", "Connectivity", "Photography" }, "<path d=\"m12.309 6.652 4.797 2.401a1 1 0 0 1 .447 1.341l-.501 1.001.605.605h2.725a1 1 0 0 1 .894 1.447l-.724 1.448\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m15.166 15.166-.719 1.439a1 1 0 0 1-1.342.447L3.61 12.3a2.92 2.92 0 0 1-1.3-3.91L3.69 5.6a2.9 2.9 0 0 1 .873-1.037\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 19h3.76a2 2 0 0 0 1.8-1.1l1.441-2.902\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 21v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 9h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("earth-lock", "EarthLock", new string[] { "vpn", "private", "privacy", "network", "world", "browser", "security", "encryption", "protection", "connection" }, new string[] { "Security", "Development", "Devices" }, "<path d=\"M7 3.34V5a3 3 0 0 0 3 3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M11 21.95V18a2 2 0 0 0-2-2 2 2 0 0 1-2-2v-1a2 2 0 0 0-2-2H2.05\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21.54 15H17a2 2 0 0 0-2 2v4.54\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2a10 10 0 1 0 9.54 13\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20 6V4a2 2 0 1 0-4 0v2\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"8\" height=\"5\" x=\"14\" y=\"6\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("globe-lock", "GlobeLock", new string[] { "vpn", "private", "privacy", "network", "world", "browser", "security", "encryption", "protection", "connection" }, new string[] { "Security", "Development", "Devices" }, "<path d=\"M15.686 15A14.5 14.5 0 0 1 12 22a14.5 14.5 0 0 1 0-20 10 10 0 1 0 9.542 13\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 12h8.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20 6V4a2 2 0 1 0-4 0v2\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"8\" height=\"5\" x=\"14\" y=\"6\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("id-card", "IdCard", new string[] { "card", "badge", "identity", "authentication", "secure" }, new string[] { "Security", "Account" }, "<path d=\"M16 10h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 14h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6.17 15a3 3 0 0 1 5.66 0\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"11\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"5\" width=\"20\" height=\"14\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("id-card-lanyard", "IdCardLanyard", new string[] { "id-card", "id-card-lanyard", "identity", "employee", "gate-pass", "badge" }, new string[] { "Security", "Account" }, "<path d=\"M13.5 8h-3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m15 2-1 2h3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16.899 22A5 5 0 0 0 7.1 22\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9 2 3 6\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"15\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("key", "Key", new string[] { "password", "login", "authentication", "secure", "unlock", "keychain", "key ring", "fob" }, new string[] { "Security", "Account" }, "<path d=\"m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 2-9.6 9.6\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"7.5\" cy=\"15.5\" r=\"5.5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("key-round", "KeyRound", new string[] { "password", "login", "authentication", "secure", "unlock" }, new string[] { "Security", "Account" }, "<path d=\"M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"16.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("key-square", "KeySquare", new string[] { "password", "login", "authentication", "secure", "unlock", "car key" }, new string[] { "Security", "Account" }, "<path d=\"M12.4 2.7a2.5 2.5 0 0 1 3.4 0l5.5 5.5a2.5 2.5 0 0 1 0 3.4l-3.7 3.7a2.5 2.5 0 0 1-3.4 0L8.7 9.8a2.5 2.5 0 0 1 0-3.4z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14 7 3 3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9.4 10.6-6.814 6.814A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("lock", "Lock", new string[] { "security", "password", "secure", "admin" }, new string[] { "Security" }, "<rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 11V7a5 5 0 0 1 10 0v4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("lock-keyhole", "LockKeyhole", new string[] { "security", "password", "secure", "admin" }, new string[] { "Security" }, "<circle cx=\"12\" cy=\"16\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"3\" y=\"10\" width=\"18\" height=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 10V7a5 5 0 0 1 10 0v3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("lock-keyhole-open", "LockKeyholeOpen", new string[] { "security" }, new string[] { "Security" }, "<circle cx=\"12\" cy=\"16\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"18\" height=\"12\" x=\"3\" y=\"10\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 10V7a5 5 0 0 1 9.33-2.5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("lock-open", "LockOpen", new string[] { "security" }, new string[] { "Security" }, "<rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 11V7a5 5 0 0 1 9.9-1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("rotate-ccw-key", "RotateCcwKey", new string[] { "password", "key", "refresh", "change" }, new string[] { "Security", "Account" }, "<path d=\"M12 7v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 9h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 12a9 9 0 1 0 9-9 9.74 9.74 0 0 0-6.74 2.74L3 8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 3v5h5\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"15\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("shield-lock", "ShieldLock", new string[] { "antivirus", "authentication", "authorization", "credentials", "cybersecurity", "data protection", "defense", "encryption", "guard", "login", "password", "privacy", "safeguard", "ssl", "tls", "two-factor authentication", "verification", "vpn" }, new string[] { "Security" }, "<path d=\"M20 9.807V6a1 1 0 00-1-1c-2 0-4.49-1.19-6.24-2.72a1.17 1.17 0 00-1.52 0C9.5 3.8 7 5 5 5a1 1 0 00-1 1v7c0 3.88 2.107 6.254 5 7.796\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 17v-2a2 2 0 00-4 0v2\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"13\" y=\"17\" width=\"8\" height=\"5\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("vault", "Vault", new string[] { "safe", "lockbox", "deposit", "locker", "coffer", "strongbox", "safety", "secure", "storage", "valuables", "bank" }, new string[] { "Security", "Travel", "Home" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"7.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7.9 7.9 2.7 2.7\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"16.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m13.4 10.6 2.7-2.7\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"7.5\" cy=\"16.5\" r=\".5\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7.9 16.1 2.7-2.7\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"16.5\" cy=\"16.5\" r=\".5\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m13.4 13.4 2.7 2.7\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("waypoints", "Waypoints", new string[] { "indirection", "vpn", "virtual private network", "proxy", "connections", "bounce", "reroute", "path", "journey", "planner", "stops", "stations", "shared", "spread", "viral" }, new string[] { "Security", "Account", "Navigation & Places", "Development", "Social" }, "<path d=\"m10.586 5.414-5.172 5.172\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m18.586 13.414-5.172 5.172\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 12h12\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"20\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"4\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"20\" cy=\"12\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"4\" cy=\"12\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
        };
    }

    internal static void RegisterSecurity(Dictionary<string, Type> registry, List<LucideIconModel> allIcons)
    {
        registry["bomb"] = typeof(LucideBomb);
        registry["Bomb"] = typeof(LucideBomb);
        registry["brick-wall-fire"] = typeof(LucideBrickWallFire);
        registry["BrickWallFire"] = typeof(LucideBrickWallFire);
        registry["brick-wall-shield"] = typeof(LucideBrickWallShield);
        registry["BrickWallShield"] = typeof(LucideBrickWallShield);
        registry["cctv"] = typeof(LucideCctv);
        registry["Cctv"] = typeof(LucideCctv);
        registry["cctv-off"] = typeof(LucideCctvOff);
        registry["CctvOff"] = typeof(LucideCctvOff);
        registry["earth-lock"] = typeof(LucideEarthLock);
        registry["EarthLock"] = typeof(LucideEarthLock);
        registry["globe-lock"] = typeof(LucideGlobeLock);
        registry["GlobeLock"] = typeof(LucideGlobeLock);
        registry["id-card"] = typeof(LucideIdCard);
        registry["IdCard"] = typeof(LucideIdCard);
        registry["id-card-lanyard"] = typeof(LucideIdCardLanyard);
        registry["IdCardLanyard"] = typeof(LucideIdCardLanyard);
        registry["key"] = typeof(LucideKey);
        registry["Key"] = typeof(LucideKey);
        registry["key-round"] = typeof(LucideKeyRound);
        registry["KeyRound"] = typeof(LucideKeyRound);
        registry["key-square"] = typeof(LucideKeySquare);
        registry["KeySquare"] = typeof(LucideKeySquare);
        registry["lock"] = typeof(LucideLock);
        registry["Lock"] = typeof(LucideLock);
        registry["lock-keyhole"] = typeof(LucideLockKeyhole);
        registry["LockKeyhole"] = typeof(LucideLockKeyhole);
        registry["lock-keyhole-open"] = typeof(LucideLockKeyholeOpen);
        registry["LockKeyholeOpen"] = typeof(LucideLockKeyholeOpen);
        registry["lock-open"] = typeof(LucideLockOpen);
        registry["LockOpen"] = typeof(LucideLockOpen);
        registry["rotate-ccw-key"] = typeof(LucideRotateCcwKey);
        registry["RotateCcwKey"] = typeof(LucideRotateCcwKey);
        registry["shield-lock"] = typeof(LucideShieldLock);
        registry["ShieldLock"] = typeof(LucideShieldLock);
        registry["vault"] = typeof(LucideVault);
        registry["Vault"] = typeof(LucideVault);
        registry["waypoints"] = typeof(LucideWaypoints);
        registry["Waypoints"] = typeof(LucideWaypoints);
        allIcons.AddRange(SecurityIcons);
    }
}
