// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public static partial class LucideRegistry
{
    private static IReadOnlyList<LucideIconModel>? _connectivityIcons;
    public static IReadOnlyList<LucideIconModel> ConnectivityIcons => _connectivityIcons ??= CreateConnectivityIcons();

    private static LucideIconModel[] CreateConnectivityIcons()
    {
        return new LucideIconModel[]
        {
            new("battery", "Battery", new string[] { "power", "electricity", "energy", "accumulator", "charge" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M 22 14 L 22 10\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"6\" width=\"16\" height=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("battery-charging", "BatteryCharging", new string[] { "power", "electricity", "energy", "accumulator", "charge" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m11 7-3 5h4l-3 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14.856 6H16a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.935\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5.14 18H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h2.936\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("battery-full", "BatteryFull", new string[] { "power", "electricity", "energy", "accumulator", "charge" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M10 10v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 10v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 10v4\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"6\" width=\"16\" height=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("battery-low", "BatteryLow", new string[] { "power", "electricity", "energy", "accumulator", "charge" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M22 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"6\" width=\"16\" height=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("battery-medium", "BatteryMedium", new string[] { "power", "electricity", "energy", "accumulator", "charge" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M10 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"6\" width=\"16\" height=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("battery-warning", "BatteryWarning", new string[] { "power", "electricity", "energy", "accumulator", "charge", "exclamation mark" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M10 17h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 7v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 6h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 14v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 18H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("bluetooth", "Bluetooth", new string[] { "wireless" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m7 7 10 10-5 5V2l5 5L7 17\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("bluetooth-connected", "BluetoothConnected", new string[] { "paired" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m7 7 10 10-5 5V2l5 5L7 17\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"18\" x2=\"21\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"3\" x2=\"6\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("bluetooth-off", "BluetoothOff", new string[] { "lost" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m17 17-5 5V12l-5 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14.5 9.5 17 7l-5-5v4.5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("bluetooth-searching", "BluetoothSearching", new string[] { "pairing" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m7 7 10 10-5 5V2l5 5L7 17\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20.83 14.83a4 4 0 0 0 0-5.66\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 12h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("cable", "Cable", new string[] { "cord", "wire", "connector", "connection", "link", "signal", "console", "computer", "equipment", "electricity", "energy", "electronics", "recharging", "charger", "power", "supply", "disconnected", "unplugged", "plugs", "interface", "input", "output", "audio video", "av", "rca", "scart", "tv", "television", "optical" }, new string[] { "Connectivity", "Devices", "Multimedia" }, "<path d=\"M17 19a1 1 0 0 1-1-1v-2a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2a1 1 0 0 1-1 1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 21v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 14V6.5a1 1 0 0 0-7 0v11a1 1 0 0 1-7 0V10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 21v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 5V3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4 10a2 2 0 0 1-2-2V6a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2a2 2 0 0 1-2 2z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 5V3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("car-battery", "CarBattery", new string[] { "battery", "automobile", "powercell", "electric", "power", "electricity", "energy", "accumulator", "charge", "transport", "vehicle", "car" }, new string[] { "Connectivity", "Transportation" }, "<path d=\"M14 13h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 15v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 5v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 13h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 5v2\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"7\" width=\"20\" height=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("card-sim", "CardSim", new string[] { "cellphone", "smartphone", "mobile", "network", "cellular", "service", "provider", "signal", "coverage", "disk", "data", "format", "storage", "flash", "digital", "contacts", "phone book", "contractual", "circuit board", "chip" }, new string[] { "Connectivity", "Communication", "Multimedia", "Devices" }, "<path d=\"M12 14v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14.172 2a2 2 0 0 1 1.414.586l3.828 3.828A2 2 0 0 1 20 7.828V20a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 14h8\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"8\" y=\"10\" width=\"8\" height=\"8\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("cassette-tape", "CassetteTape", new string[] { "audio", "music", "recording", "play" }, new string[] { "Connectivity", "Devices", "Multimedia", "Communication", "Files" }, "<rect width=\"20\" height=\"16\" x=\"2\" y=\"4\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"8\" cy=\"10\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 12h8\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"16\" cy=\"10\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m6 20 .7-2.9A1.4 1.4 0 0 1 8.1 16h7.8a1.4 1.4 0 0 1 1.4 1l.7 3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("circle-power", "CirclePower", new string[] { "on", "off", "device", "switch", "toggle", "binary", "boolean", "reboot", "restart", "button", "keyboard", "troubleshoot" }, new string[] { "Connectivity" }, "<circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 7v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7.998 9.003a5 5 0 1 0 8-.005\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("cloud-off", "CloudOff", new string[] { "disconnect" }, new string[] { "Connectivity", "Weather" }, "<path d=\"M10.94 5.274A7 7 0 0 1 15.71 10h1.79a4.5 4.5 0 0 1 4.222 6.057\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18.796 18.81A4.5 4.5 0 0 1 17.5 19H9A7 7 0 0 1 5.79 5.78\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("globe-x", "GlobeX", new string[] { "globe", "internet", "offline", "disconnected", "network", "connection", "world", "no connection", "network failure", "signal off" }, new string[] { "Connectivity", "Devices", "Navigation & Places" }, "<path d=\"m16 3 5 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 12h20A10 10 0 1 1 12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 4-10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 3-5 5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor", "Monitor", new string[] { "tv", "screen", "display", "virtual machine", "vm" }, new string[] { "Connectivity", "Devices" }, "<rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"8\" x2=\"16\" y1=\"21\" y2=\"21\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"12\" x2=\"12\" y1=\"17\" y2=\"21\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-check", "MonitorCheck", new string[] { "tv", "screen", "display", "desktop", "running", "active", "virtual machine", "vm" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m9 10 2 2 4-4\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-cloud", "MonitorCloud", new string[] { "virtual machine", "virtual desktop", "vm", "vdi", "computing", "remote work", "monitoring", "infrastructure", "software as a service", "saas", "workstation", "environment", "tv", "screen", "display" }, new string[] { "Connectivity", "Devices", "Development" }, "<path d=\"M11 13a3 3 0 1 1 2.83-4H14a2 2 0 0 1 0 4z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-cog", "MonitorCog", new string[] { "tv", "screen", "display", "virtual machine", "vm", "executable", "settings", "cog", "edit", "gear", "configuration", "preferences", "system", "control panel", "network", "computing" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14.305 7.53.923-.382\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m15.228 4.852-.923-.383\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16.852 3.228-.383-.924\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16.852 8.772-.383.923\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m19.148 3.228.383-.924\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m19.53 9.696-.382-.924\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20.772 4.852.924-.383\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20.772 7.148.924.383\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 13v2a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"18\" cy=\"6\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-dot", "MonitorDot", new string[] { "tv", "screen", "display", "desktop", "running", "active", "virtual machine", "vm" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 12.307V15a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h8.693\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"19\" cy=\"6\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-down", "MonitorDown", new string[] { "tv", "screen", "display", "desktop", "download" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 13V7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m15 10-3 3-3-3\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-off", "MonitorOff", new string[] { "share" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 1.184-1.826\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.656 3H20a2 2 0 0 1 2 2v10a2 2 0 0 1-.293 1.042\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-pause", "MonitorPause", new string[] { "tv", "screen", "display", "desktop", "video", "movie", "film", "suspend", "hibernate", "boot", "virtual machine", "vm" }, new string[] { "Connectivity", "Devices", "Multimedia" }, "<path d=\"M10 13V7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 13V7\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-play", "MonitorPlay", new string[] { "tv", "screen", "display", "desktop", "video", "movie", "film", "running", "start", "boot", "virtual machine", "vm" }, new string[] { "Connectivity", "Devices", "Multimedia" }, "<path d=\"M15.033 9.44a.647.647 0 0 1 0 1.12l-4.065 2.352a.645.645 0 0 1-.968-.56V7.648a.645.645 0 0 1 .967-.56z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-smartphone", "MonitorSmartphone", new string[] { "smartphone", "phone", "cellphone", "device", "mobile", "desktop", "monitor", "responsive", "screens" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M18 8V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 19v-3.96 3.15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 19h5\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"6\" height=\"10\" x=\"16\" y=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-speaker", "MonitorSpeaker", new string[] { "devices", "connect", "cast" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M5.5 20H8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 9h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"10\" height=\"16\" x=\"12\" y=\"4\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 6H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h4\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"17\" cy=\"15\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-stop", "MonitorStop", new string[] { "tv", "screen", "display", "desktop", "video", "movie", "film", "stop", "shutdown", "virtual machine", "vm" }, new string[] { "Connectivity", "Devices", "Multimedia" }, "<path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"9\" y=\"7\" width=\"6\" height=\"6\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-up", "MonitorUp", new string[] { "tv", "screen", "display", "upload", "connect", "remote", "screen share" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m9 10 3-3 3 3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 13V7\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("monitor-x", "MonitorX", new string[] { "tv", "screen", "display", "desktop", "virtual machine", "vm", "close", "stop", "suspend", "remove", "delete" }, new string[] { "Connectivity", "Devices" }, "<path d=\"m14.5 12.5-5-5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9.5 12.5 5-5\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("phone-call", "PhoneCall", new string[] { "ring" }, new string[] { "Connectivity", "Devices", "Communication" }, "<path d=\"M13 2a9 9 0 0 1 9 9\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M13 6a5 5 0 0 1 5 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("phone-missed", "PhoneMissed", new string[] { "call" }, new string[] { "Connectivity", "Devices", "Communication" }, "<path d=\"m16 2 6 6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m22 2-6 6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("phone-off", "PhoneOff", new string[] { "call", "mute" }, new string[] { "Connectivity", "Devices", "Communication" }, "<path d=\"M10.1 13.9a14 14 0 0 0 3.732 2.668 1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2 18 18 0 0 1-12.728-5.272\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 2 2 22\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4.76 13.582A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 .244.473\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("power", "Power", new string[] { "on", "off", "device", "switch", "toggle", "binary", "boolean", "reboot", "restart", "button", "keyboard", "troubleshoot" }, new string[] { "Connectivity" }, "<path d=\"M12 2v10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18.4 6.6a9 9 0 1 1-12.77.04\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("power-off", "PowerOff", new string[] { "on", "off", "device", "switch" }, new string[] { "Connectivity" }, "<path d=\"M18.36 6.64A9 9 0 0 1 20.77 15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6.16 6.16a9 9 0 1 0 12.68 12.68\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("satellite", "Satellite", new string[] { "space station", "orbit", "transmitter" }, new string[] { "Connectivity", "Science" }, "<path d=\"m13.5 6.5-3.148-3.148a1.205 1.205 0 0 0-1.704 0L6.352 5.648a1.205 1.205 0 0 0 0 1.704L9.5 10.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16.5 7.5 19 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17.5 10.5 3.148 3.148a1.205 1.205 0 0 1 0 1.704l-2.296 2.296a1.205 1.205 0 0 1-1.704 0L13.5 14.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 21a6 6 0 0 0-6-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.352 10.648a1.205 1.205 0 0 0 0 1.704l2.296 2.296a1.205 1.205 0 0 0 1.704 0l4.296-4.296a1.205 1.205 0 0 0 0-1.704l-2.296-2.296a1.205 1.205 0 0 0-1.704 0z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("satellite-dish", "SatelliteDish", new string[] { "antenna", "receiver", "dish aerial", "saucer" }, new string[] { "Connectivity", "Devices", "Multimedia" }, "<path d=\"M4 10a7.31 7.31 0 0 0 10 10Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9 15 3-3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 13a6 6 0 0 0-6-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 13A10 10 0 0 0 11 3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("screen-share", "ScreenShare", new string[] { "host", "desktop", "monitor" }, new string[] { "Connectivity", "Devices", "Communication" }, "<path d=\"M13 3H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17 8 5-5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3h5v5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("screen-share-off", "ScreenShareOff", new string[] { "desktop", "disconnect", "monitor" }, new string[] { "Connectivity", "Devices", "Communication" }, "<path d=\"M13 3H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m22 3-5 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17 3 5 5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("signal", "Signal", new string[] { "connection", "wireless", "gsm", "phone", "2g", "3g", "4g", "5g" }, new string[] { "Connectivity" }, "<path d=\"M2 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 20v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 20v-8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 20V8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 4v16\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("signal-high", "SignalHigh", new string[] { "connection", "wireless", "gsm", "phone", "2g", "3g", "4g", "5g" }, new string[] { "Connectivity" }, "<path d=\"M2 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 20v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 20v-8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 20V8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("signal-low", "SignalLow", new string[] { "connection", "wireless", "gsm", "phone", "2g", "3g", "4g", "5g" }, new string[] { "Connectivity" }, "<path d=\"M2 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 20v-4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("signal-medium", "SignalMedium", new string[] { "connection", "wireless", "gsm", "phone", "2g", "3g", "4g", "5g" }, new string[] { "Connectivity" }, "<path d=\"M2 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 20v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 20v-8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("signal-zero", "SignalZero", new string[] { "connection", "wireless", "gsm", "phone", "2g", "3g", "4g", "5g", "lost" }, new string[] { "Connectivity" }, "<path d=\"M2 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("smartphone", "Smartphone", new string[] { "phone", "cellphone", "device", "screen" }, new string[] { "Connectivity", "Devices" }, "<rect width=\"14\" height=\"20\" x=\"5\" y=\"2\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 18h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("smartphone-charging", "SmartphoneCharging", new string[] { "phone", "cellphone", "device", "power", "screen" }, new string[] { "Connectivity", "Devices" }, "<rect width=\"14\" height=\"20\" x=\"5\" y=\"2\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12.667 8 10 12h4l-2.667 4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("square-power", "SquarePower", new string[] { "on", "off", "device", "switch", "toggle", "binary", "boolean", "reboot", "restart", "button", "keyboard", "troubleshoot" }, new string[] { "Connectivity" }, "<path d=\"M12 7v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7.998 9.003a5 5 0 1 0 8-.005\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("voicemail", "Voicemail", new string[] { "phone", "cassette", "tape", "reel", "recording", "audio" }, new string[] { "Connectivity", "Devices", "Social" }, "<circle cx=\"6\" cy=\"12\" r=\"4\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"18\" cy=\"12\" r=\"4\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"6\" x2=\"18\" y1=\"16\" y2=\"16\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("volume", "Volume", new string[] { "music", "sound", "mute", "speaker" }, new string[] { "Connectivity", "Communication", "Multimedia" }, "<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("volume-1", "Volume1", new string[] { "music", "sound", "speaker" }, new string[] { "Connectivity", "Communication", "Multimedia" }, "<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 9a5 5 0 0 1 0 6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("volume-2", "Volume2", new string[] { "music", "sound", "speaker" }, new string[] { "Connectivity", "Communication", "Multimedia" }, "<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 9a5 5 0 0 1 0 6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19.364 18.364a9 9 0 0 0 0-12.728\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("volume-off", "VolumeOff", new string[] { "music", "sound", "mute", "speaker" }, new string[] { "Connectivity", "Communication", "Multimedia" }, "<path d=\"M16 9a5 5 0 0 1 .95 2.293\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19.364 5.636a9 9 0 0 1 1.889 9.96\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7 7-.587.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298V11\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.828 4.172A.686.686 0 0 1 11 4.657v.686\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("volume-x", "VolumeX", new string[] { "music", "sound", "mute", "speaker" }, new string[] { "Connectivity", "Communication", "Multimedia" }, "<path d=\"M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"22\" x2=\"16\" y1=\"9\" y2=\"15\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"16\" x2=\"22\" y1=\"9\" y2=\"15\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("webcam", "Webcam", new string[] { "camera", "security" }, new string[] { "Connectivity", "Devices", "Communication" }, "<circle cx=\"12\" cy=\"10\" r=\"8\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 22h10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 22v-4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("webcam-off", "WebcamOff", new string[] { "camera", "security" }, new string[] { "Connectivity", "Devices", "Communication" }, "<path d=\"M12 22v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12.754 7.096a3 3 0 0 1 2.15 2.15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12.863 12.873a3 3 0 0 1-3.736-3.735\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16.566 16.57A8 8 0 0 1 5.43 5.433\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 22h10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.478 2.817a8 8 0 0 1 10.705 10.705\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi", "Wifi", new string[] { "connection", "signal", "wireless" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 8.82a15 15 0 0 1 20 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 12.859a10 10 0 0 1 14 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi-cog", "WifiCog", new string[] { "connection", "signal", "wireless", "directory", "settings", "control", "preferences", "cog", "edit", "gear" }, new string[] { "Connectivity", "Devices", "Files" }, "<path d=\"m14.305 19.53.923-.382\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m15.228 16.852-.923-.383\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16.852 15.228-.383-.923\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16.852 20.772-.383.924\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m19.148 15.228.383-.923\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m19.53 21.696-.382-.924\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 7.82a15 15 0 0 1 20 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20.772 16.852.924-.383\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20.772 19.148.924.383\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 11.858a10 10 0 0 1 11.5-1.785\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.5 15.429a5 5 0 0 1 2.413-1.31\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"18\" cy=\"18\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi-high", "WifiHigh", new string[] { "connection", "signal", "wireless" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 12.859a10 10 0 0 1 14 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi-low", "WifiLow", new string[] { "connection", "signal", "wireless" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi-off", "WifiOff", new string[] { "disabled" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.5 16.429a5 5 0 0 1 7 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 12.859a10 10 0 0 1 5.17-2.69\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 12.859a10 10 0 0 0-2.007-1.523\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 8.82a15 15 0 0 1 4.177-2.643\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 8.82a15 15 0 0 0-11.288-3.764\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi-pen", "WifiPen", new string[] { "edit", "wifi", "pen", "change", "network" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M2 8.82a15 15 0 0 1 20 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 12.859a10 10 0 0 1 10.5-2.222\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.5 16.429a5 5 0 0 1 3-1.406\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi-sync", "WifiSync", new string[] { "connection", "signal", "wireless", "synchronize", "reconnect", "reset", "restart" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M11.965 10.105v4L13.5 12.5a5 5 0 0 1 8 1.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M11.965 14.105h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.965 18.105h4L20.43 19.71a5 5 0 0 1-8-1.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 8.82a15 15 0 0 1 20 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21.965 22.105v-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 12.86a10 10 0 0 1 3-2.032\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.5 16.429h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("wifi-zero", "WifiZero", new string[] { "connection", "signal", "wireless" }, new string[] { "Connectivity", "Devices" }, "<path d=\"M12 20h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("zap", "Zap", new string[] { "flash", "camera", "lightning", "electricity", "energy", "power", "quick" }, new string[] { "Connectivity", "Devices", "Photography", "Weather" }, "<path d=\"M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("zap-off", "ZapOff", new string[] { "flash", "camera", "lightning", "electricity", "energy", "power" }, new string[] { "Connectivity", "Devices", "Photography", "Weather" }, "<path d=\"M10.768 5.111 13.44 2.44a1.5 1.5 0 012.474 1.561l-1.633 4.625\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m18.889 13.232.672-.672A1.5 1.5 0 0018.5 10h-2.844\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7.94 7.94-3.5 3.499A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l5.5-5.5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
        };
    }

    internal static void RegisterConnectivity(Dictionary<string, Type> registry, List<LucideIconModel> allIcons)
    {
        registry["battery"] = typeof(LucideBattery);
        registry["Battery"] = typeof(LucideBattery);
        registry["battery-charging"] = typeof(LucideBatteryCharging);
        registry["BatteryCharging"] = typeof(LucideBatteryCharging);
        registry["battery-full"] = typeof(LucideBatteryFull);
        registry["BatteryFull"] = typeof(LucideBatteryFull);
        registry["battery-low"] = typeof(LucideBatteryLow);
        registry["BatteryLow"] = typeof(LucideBatteryLow);
        registry["battery-medium"] = typeof(LucideBatteryMedium);
        registry["BatteryMedium"] = typeof(LucideBatteryMedium);
        registry["battery-warning"] = typeof(LucideBatteryWarning);
        registry["BatteryWarning"] = typeof(LucideBatteryWarning);
        registry["bluetooth"] = typeof(LucideBluetooth);
        registry["Bluetooth"] = typeof(LucideBluetooth);
        registry["bluetooth-connected"] = typeof(LucideBluetoothConnected);
        registry["BluetoothConnected"] = typeof(LucideBluetoothConnected);
        registry["bluetooth-off"] = typeof(LucideBluetoothOff);
        registry["BluetoothOff"] = typeof(LucideBluetoothOff);
        registry["bluetooth-searching"] = typeof(LucideBluetoothSearching);
        registry["BluetoothSearching"] = typeof(LucideBluetoothSearching);
        registry["cable"] = typeof(LucideCable);
        registry["Cable"] = typeof(LucideCable);
        registry["car-battery"] = typeof(LucideCarBattery);
        registry["CarBattery"] = typeof(LucideCarBattery);
        registry["card-sim"] = typeof(LucideCardSim);
        registry["CardSim"] = typeof(LucideCardSim);
        registry["cassette-tape"] = typeof(LucideCassetteTape);
        registry["CassetteTape"] = typeof(LucideCassetteTape);
        registry["circle-power"] = typeof(LucideCirclePower);
        registry["CirclePower"] = typeof(LucideCirclePower);
        registry["cloud-off"] = typeof(LucideCloudOff);
        registry["CloudOff"] = typeof(LucideCloudOff);
        registry["globe-x"] = typeof(LucideGlobeX);
        registry["GlobeX"] = typeof(LucideGlobeX);
        registry["monitor"] = typeof(LucideMonitor);
        registry["Monitor"] = typeof(LucideMonitor);
        registry["monitor-check"] = typeof(LucideMonitorCheck);
        registry["MonitorCheck"] = typeof(LucideMonitorCheck);
        registry["monitor-cloud"] = typeof(LucideMonitorCloud);
        registry["MonitorCloud"] = typeof(LucideMonitorCloud);
        registry["monitor-cog"] = typeof(LucideMonitorCog);
        registry["MonitorCog"] = typeof(LucideMonitorCog);
        registry["monitor-dot"] = typeof(LucideMonitorDot);
        registry["MonitorDot"] = typeof(LucideMonitorDot);
        registry["monitor-down"] = typeof(LucideMonitorDown);
        registry["MonitorDown"] = typeof(LucideMonitorDown);
        registry["monitor-off"] = typeof(LucideMonitorOff);
        registry["MonitorOff"] = typeof(LucideMonitorOff);
        registry["monitor-pause"] = typeof(LucideMonitorPause);
        registry["MonitorPause"] = typeof(LucideMonitorPause);
        registry["monitor-play"] = typeof(LucideMonitorPlay);
        registry["MonitorPlay"] = typeof(LucideMonitorPlay);
        registry["monitor-smartphone"] = typeof(LucideMonitorSmartphone);
        registry["MonitorSmartphone"] = typeof(LucideMonitorSmartphone);
        registry["monitor-speaker"] = typeof(LucideMonitorSpeaker);
        registry["MonitorSpeaker"] = typeof(LucideMonitorSpeaker);
        registry["monitor-stop"] = typeof(LucideMonitorStop);
        registry["MonitorStop"] = typeof(LucideMonitorStop);
        registry["monitor-up"] = typeof(LucideMonitorUp);
        registry["MonitorUp"] = typeof(LucideMonitorUp);
        registry["monitor-x"] = typeof(LucideMonitorX);
        registry["MonitorX"] = typeof(LucideMonitorX);
        registry["phone-call"] = typeof(LucidePhoneCall);
        registry["PhoneCall"] = typeof(LucidePhoneCall);
        registry["phone-missed"] = typeof(LucidePhoneMissed);
        registry["PhoneMissed"] = typeof(LucidePhoneMissed);
        registry["phone-off"] = typeof(LucidePhoneOff);
        registry["PhoneOff"] = typeof(LucidePhoneOff);
        registry["power"] = typeof(LucidePower);
        registry["Power"] = typeof(LucidePower);
        registry["power-off"] = typeof(LucidePowerOff);
        registry["PowerOff"] = typeof(LucidePowerOff);
        registry["satellite"] = typeof(LucideSatellite);
        registry["Satellite"] = typeof(LucideSatellite);
        registry["satellite-dish"] = typeof(LucideSatelliteDish);
        registry["SatelliteDish"] = typeof(LucideSatelliteDish);
        registry["screen-share"] = typeof(LucideScreenShare);
        registry["ScreenShare"] = typeof(LucideScreenShare);
        registry["screen-share-off"] = typeof(LucideScreenShareOff);
        registry["ScreenShareOff"] = typeof(LucideScreenShareOff);
        registry["signal"] = typeof(LucideSignal);
        registry["Signal"] = typeof(LucideSignal);
        registry["signal-high"] = typeof(LucideSignalHigh);
        registry["SignalHigh"] = typeof(LucideSignalHigh);
        registry["signal-low"] = typeof(LucideSignalLow);
        registry["SignalLow"] = typeof(LucideSignalLow);
        registry["signal-medium"] = typeof(LucideSignalMedium);
        registry["SignalMedium"] = typeof(LucideSignalMedium);
        registry["signal-zero"] = typeof(LucideSignalZero);
        registry["SignalZero"] = typeof(LucideSignalZero);
        registry["smartphone"] = typeof(LucideSmartphone);
        registry["Smartphone"] = typeof(LucideSmartphone);
        registry["smartphone-charging"] = typeof(LucideSmartphoneCharging);
        registry["SmartphoneCharging"] = typeof(LucideSmartphoneCharging);
        registry["square-power"] = typeof(LucideSquarePower);
        registry["SquarePower"] = typeof(LucideSquarePower);
        registry["voicemail"] = typeof(LucideVoicemail);
        registry["Voicemail"] = typeof(LucideVoicemail);
        registry["volume"] = typeof(LucideVolume);
        registry["Volume"] = typeof(LucideVolume);
        registry["volume-1"] = typeof(LucideVolume1);
        registry["Volume1"] = typeof(LucideVolume1);
        registry["volume-2"] = typeof(LucideVolume2);
        registry["Volume2"] = typeof(LucideVolume2);
        registry["volume-off"] = typeof(LucideVolumeOff);
        registry["VolumeOff"] = typeof(LucideVolumeOff);
        registry["volume-x"] = typeof(LucideVolumeX);
        registry["VolumeX"] = typeof(LucideVolumeX);
        registry["webcam"] = typeof(LucideWebcam);
        registry["Webcam"] = typeof(LucideWebcam);
        registry["webcam-off"] = typeof(LucideWebcamOff);
        registry["WebcamOff"] = typeof(LucideWebcamOff);
        registry["wifi"] = typeof(LucideWifi);
        registry["Wifi"] = typeof(LucideWifi);
        registry["wifi-cog"] = typeof(LucideWifiCog);
        registry["WifiCog"] = typeof(LucideWifiCog);
        registry["wifi-high"] = typeof(LucideWifiHigh);
        registry["WifiHigh"] = typeof(LucideWifiHigh);
        registry["wifi-low"] = typeof(LucideWifiLow);
        registry["WifiLow"] = typeof(LucideWifiLow);
        registry["wifi-off"] = typeof(LucideWifiOff);
        registry["WifiOff"] = typeof(LucideWifiOff);
        registry["wifi-pen"] = typeof(LucideWifiPen);
        registry["WifiPen"] = typeof(LucideWifiPen);
        registry["wifi-sync"] = typeof(LucideWifiSync);
        registry["WifiSync"] = typeof(LucideWifiSync);
        registry["wifi-zero"] = typeof(LucideWifiZero);
        registry["WifiZero"] = typeof(LucideWifiZero);
        registry["zap"] = typeof(LucideZap);
        registry["Zap"] = typeof(LucideZap);
        registry["zap-off"] = typeof(LucideZapOff);
        registry["ZapOff"] = typeof(LucideZapOff);
        allIcons.AddRange(ConnectivityIcons);
    }
}
