// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public static partial class LucideRegistry
{
    private static IReadOnlyList<LucideIconModel>? _photographyIcons;
    public static IReadOnlyList<LucideIconModel> PhotographyIcons => _photographyIcons ??= CreatePhotographyIcons();

    private static LucideIconModel[] CreatePhotographyIcons()
    {
        return new LucideIconModel[]
        {
            new("album", "Album", new string[] { "photo", "book" }, new string[] { "Photography", "Multimedia" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><polyline points=\"11 3 11 11 14 8 17 11 17 3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("aperture", "Aperture", new string[] { "camera", "photo", "pictures", "shutter", "exposure" }, new string[] { "Photography" }, "<circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14.31 8 5.74 9.94\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.69 8h11.48\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7.38 12 5.74-9.94\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.69 16 3.95 6.06\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14.31 16H2.83\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16.62 12-5.74 9.94\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("book-image", "BookImage", new string[] { "images", "pictures", "photos", "album", "collection", "event", "magazine", "catalog", "catalogue", "brochure", "browse", "gallery" }, new string[] { "Photography", "Text formatting", "Multimedia", "Files", "Social", "Shopping", "Travel" }, "<path d=\"m20 13.7-2.1-2.1a2 2 0 0 0-2.8 0L9.7 17\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H19a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1H6.5a1 1 0 0 1 0-5H20\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"10\" cy=\"8\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("camera", "Camera", new string[] { "photography", "lens", "focus", "capture", "shot", "visual", "image", "device", "equipment", "photo", "webcam", "video" }, new string[] { "Photography", "Devices", "Communication" }, "<path d=\"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"13\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("camera-off", "CameraOff", new string[] { "photo", "webcam", "video" }, new string[] { "Photography", "Devices", "Communication" }, "<path d=\"M14.564 14.558a3 3 0 1 1-4.122-4.121\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20 20H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 .819-.175\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.695 4.024A2 2 0 0 1 10.004 4h3.993a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v7.344\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("contrast", "Contrast", new string[] { "display", "accessibility" }, new string[] { "Photography", "Accessibility", "Design" }, "<circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 18a6 6 0 0 0 0-12v12z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("crop", "Crop", new string[] { "photo", "image" }, new string[] { "Photography", "Design" }, "<path d=\"M6 2v14a2 2 0 0 0 2 2h14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 22V8a2 2 0 0 0-2-2H2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("crosshair", "Crosshair", new string[] { "aim", "target" }, new string[] { "Photography" }, "<circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"22\" x2=\"18\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"6\" x2=\"2\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"12\" x2=\"12\" y1=\"6\" y2=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"12\" x2=\"12\" y1=\"22\" y2=\"18\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("film", "Film", new string[] { "movie", "video", "reel", "camera", "cinema", "entertainment" }, new string[] { "Photography", "Multimedia" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 3v18\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 7.5h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 12h18\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 16.5h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3v18\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 7.5h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 16.5h4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("flashlight", "Flashlight", new string[] { "torch", "light", "beam", "emergency", "safety", "tool", "bright" }, new string[] { "Photography", "Devices" }, "<path d=\"M12 13v1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 2a1 1 0 0 1 1 1v4a3 3 0 0 1-.6 1.8l-.6.8A4 4 0 0 0 16 12v8a2 2 0 0 1-2 2H10a2 2 0 0 1-2-2v-8a4 4 0 0 0-.8-2.4l-.6-.8A3 3 0 0 1 6 7V3a1 1 0 0 1 1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 6h12\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("flashlight-off", "FlashlightOff", new string[] { "torch", "light", "beam", "emergency", "safety", "tool", "bright" }, new string[] { "Photography", "Devices" }, "<path d=\"M11.652 6H18\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 13v1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 16v4a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2v-8a4 4 0 0 0-.8-2.4l-.6-.8A3 3 0 0 1 6 7V6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7.649 2H17a1 1 0 0 1 1 1v4a3 3 0 0 1-.6 1.8l-.6.8a4 4 0 0 0-.55 1.007\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("focus", "Focus", new string[] { "camera", "lens", "photo", "dashed" }, new string[] { "Photography" }, "<circle cx=\"12\" cy=\"12\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 7V5a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image", "Image", new string[] { "picture", "photo" }, new string[] { "Photography", "Text formatting", "Multimedia", "Files" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"9\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image-down", "ImageDown", new string[] { "picture", "photo", "download", "save", "export" }, new string[] { "Photography", "Text formatting", "Multimedia", "Files" }, "<path d=\"M10.3 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v10l-3.1-3.1a2 2 0 0 0-2.814.014L6 21\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14 19 3 3v-5.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17 22 3-3\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"9\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image-minus", "ImageMinus", new string[] { "remove", "delete" }, new string[] { "Photography", "Multimedia", "Files" }, "<path d=\"M21 9v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"16\" x2=\"22\" y1=\"5\" y2=\"5\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"9\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image-off", "ImageOff", new string[] { "picture", "photo" }, new string[] { "Photography", "Multimedia", "Files" }, "<line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10.41 10.41a2 2 0 1 1-2.83-2.83\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"13.5\" x2=\"6\" y1=\"13.5\" y2=\"21\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"18\" x2=\"21\" y1=\"12\" y2=\"15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 15V5a2 2 0 0 0-2-2H9\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image-play", "ImagePlay", new string[] { "picture", "gif", "photo" }, new string[] { "Photography", "Text formatting", "Multimedia", "Files" }, "<path d=\"M15 15.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997a1 1 0 0 1-1.517-.86z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 12.17V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m6 21 5-5\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"9\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image-plus", "ImagePlus", new string[] { "add", "create", "picture" }, new string[] { "Photography", "Multimedia", "Files" }, "<path d=\"M16 5h6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 2v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 11.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"9\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image-up", "ImageUp", new string[] { "picture", "photo", "upload", "import" }, new string[] { "Photography", "Text formatting", "Multimedia", "Files" }, "<path d=\"M10.3 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v10l-3.1-3.1a2 2 0 0 0-2.814.014L6 21\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14 19.5 3-3 3 3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 22v-5.5\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"9\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("image-upscale", "ImageUpscale", new string[] { "resize", "picture", "sharpen", "increase" }, new string[] { "Photography", "Multimedia" }, "<path d=\"M16 3h5v5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 21h2a2 2 0 0 0 2-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 12v3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 3-5 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 7V5a2 2 0 0 1 2-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m5 21 4.144-4.144a1.21 1.21 0 0 1 1.712 0L13 19\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 3h3\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"3\" y=\"11\" width=\"10\" height=\"10\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("images", "Images", new string[] { "picture", "photo", "multiple", "copy", "gallery", "album", "collection", "slideshow", "showcase" }, new string[] { "Photography", "Text formatting", "Multimedia", "Files" }, "<path d=\"m22 11-1.296-1.296a2.4 2.4 0 0 0-3.408 0L11 16\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4 8a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"13\" cy=\"7\" r=\"1\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"8\" y=\"2\" width=\"14\" height=\"14\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("lightbulb", "Lightbulb", new string[] { "idea", "bright", "lights" }, new string[] { "Photography" }, "<path d=\"M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 18h6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 22h4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("lightbulb-off", "LightbulbOff", new string[] { "lights" }, new string[] { "Photography" }, "<path d=\"M16.8 11.2c.8-.9 1.2-2 1.2-3.2a6 6 0 0 0-9.3-5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6.3 6.3a4.67 4.67 0 0 0 1.2 5.2c.7.7 1.3 1.5 1.5 2.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 18h6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 22h4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scan-eye", "ScanEye", new string[] { "preview", "zoom", "expand", "fullscreen", "gallery", "image", "camera", "watch", "surveillance", "retina", "focus", "lens", "biometric", "identification", "authentication", "access", "login" }, new string[] { "Photography", "Multimedia", "Accessibility", "Security", "Devices", "Account" }, "<path d=\"M3 7V5a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18.944 12.33a1 1 0 0 0 0-.66 7.5 7.5 0 0 0-13.888 0 1 1 0 0 0 0 .66 7.5 7.5 0 0 0 13.888 0\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scan-search", "ScanSearch", new string[] { "preview", "zoom", "expand", "fullscreen", "gallery", "image", "focus", "lens" }, new string[] { "Photography", "Multimedia", "Accessibility" }, "<path d=\"M3 7V5a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16 16-1.9-1.9\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scan-square", "ScanSquare", new string[] { "scan", "square", "detect", "recognition", "select", "frame", "object", "viewfinder", "capture", "shape", "boundary", "camera", "scanner", "overlay", "focus", "crop", "marker" }, new string[] { "Photography", "Design", "Development" }, "<path d=\"M3 7V5a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"8\" height=\"8\" x=\"8\" y=\"8\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
        };
    }

    internal static void RegisterPhotography(Dictionary<string, Type> registry, List<LucideIconModel> allIcons)
    {
        registry["album"] = typeof(LucideAlbum);
        registry["Album"] = typeof(LucideAlbum);
        registry["aperture"] = typeof(LucideAperture);
        registry["Aperture"] = typeof(LucideAperture);
        registry["book-image"] = typeof(LucideBookImage);
        registry["BookImage"] = typeof(LucideBookImage);
        registry["camera"] = typeof(LucideCamera);
        registry["Camera"] = typeof(LucideCamera);
        registry["camera-off"] = typeof(LucideCameraOff);
        registry["CameraOff"] = typeof(LucideCameraOff);
        registry["contrast"] = typeof(LucideContrast);
        registry["Contrast"] = typeof(LucideContrast);
        registry["crop"] = typeof(LucideCrop);
        registry["Crop"] = typeof(LucideCrop);
        registry["crosshair"] = typeof(LucideCrosshair);
        registry["Crosshair"] = typeof(LucideCrosshair);
        registry["film"] = typeof(LucideFilm);
        registry["Film"] = typeof(LucideFilm);
        registry["flashlight"] = typeof(LucideFlashlight);
        registry["Flashlight"] = typeof(LucideFlashlight);
        registry["flashlight-off"] = typeof(LucideFlashlightOff);
        registry["FlashlightOff"] = typeof(LucideFlashlightOff);
        registry["focus"] = typeof(LucideFocus);
        registry["Focus"] = typeof(LucideFocus);
        registry["image"] = typeof(LucideImage);
        registry["Image"] = typeof(LucideImage);
        registry["image-down"] = typeof(LucideImageDown);
        registry["ImageDown"] = typeof(LucideImageDown);
        registry["image-minus"] = typeof(LucideImageMinus);
        registry["ImageMinus"] = typeof(LucideImageMinus);
        registry["image-off"] = typeof(LucideImageOff);
        registry["ImageOff"] = typeof(LucideImageOff);
        registry["image-play"] = typeof(LucideImagePlay);
        registry["ImagePlay"] = typeof(LucideImagePlay);
        registry["image-plus"] = typeof(LucideImagePlus);
        registry["ImagePlus"] = typeof(LucideImagePlus);
        registry["image-up"] = typeof(LucideImageUp);
        registry["ImageUp"] = typeof(LucideImageUp);
        registry["image-upscale"] = typeof(LucideImageUpscale);
        registry["ImageUpscale"] = typeof(LucideImageUpscale);
        registry["images"] = typeof(LucideImages);
        registry["Images"] = typeof(LucideImages);
        registry["lightbulb"] = typeof(LucideLightbulb);
        registry["Lightbulb"] = typeof(LucideLightbulb);
        registry["lightbulb-off"] = typeof(LucideLightbulbOff);
        registry["LightbulbOff"] = typeof(LucideLightbulbOff);
        registry["scan-eye"] = typeof(LucideScanEye);
        registry["ScanEye"] = typeof(LucideScanEye);
        registry["scan-search"] = typeof(LucideScanSearch);
        registry["ScanSearch"] = typeof(LucideScanSearch);
        registry["scan-square"] = typeof(LucideScanSquare);
        registry["ScanSquare"] = typeof(LucideScanSquare);
        allIcons.AddRange(PhotographyIcons);
    }
}
