// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public static partial class LucideRegistry
{
    private static IReadOnlyList<LucideIconModel>? _navigationAndPlacesIcons;
    public static IReadOnlyList<LucideIconModel> NavigationAndPlacesIcons => _navigationAndPlacesIcons ??= CreateNavigationAndPlacesIcons();

    private static LucideIconModel[] CreateNavigationAndPlacesIcons()
    {
        return new LucideIconModel[]
        {
            new("binoculars", "Binoculars", new string[] { "field glasses", "lorgnette", "pince-nez", "observation", "sightseeing", "nature", "wildlife", "birdwatching", "scouting", "surveillance", "search", "discovery", "monitoring", "lookout", "viewpoint", "travel", "tourism", "research" }, new string[] { "Navigation & Places", "Nature", "Photography", "Science", "Travel", "Development" }, "<path d=\"M10 10h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 7V4a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20 21a2 2 0 0 0 2-2v-3.851c0-1.39-2-2.962-2-4.829V8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v11a2 2 0 0 0 2 2z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M 22 16 L 2 16\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4 21a2 2 0 0 1-2-2v-3.851c0-1.39 2-2.962 2-4.829V8a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v11a2 2 0 0 1-2 2z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 7V4a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("compass", "Compass", new string[] { "direction", "north", "east", "south", "west", "browser" }, new string[] { "Navigation & Places", "Travel" }, "<circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dumbbell", "Dumbbell", new string[] { "barbell", "weight", "workout", "gym" }, new string[] { "Navigation & Places", "Sports" }, "<path d=\"M17.596 12.768a2 2 0 1 0 2.829-2.829l-1.768-1.767a2 2 0 0 0 2.828-2.829l-2.828-2.828a2 2 0 0 0-2.829 2.828l-1.767-1.768a2 2 0 1 0-2.829 2.829z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2.5 21.5 1.4-1.4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20.1 3.9 1.4-1.4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5.343 21.485a2 2 0 1 0 2.829-2.828l1.767 1.768a2 2 0 1 0 2.829-2.829l-6.364-6.364a2 2 0 1 0-2.829 2.829l1.768 1.767a2 2 0 0 0-2.828 2.829z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9.6 14.4 4.8-4.8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("earth", "Earth", new string[] { "world", "browser", "language", "translate", "globe" }, new string[] { "Navigation & Places" }, "<path d=\"M21.54 15H17a2 2 0 0 0-2 2v4.54\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 3.34V5a3 3 0 0 0 3 3a2 2 0 0 1 2 2c0 1.1.9 2 2 2a2 2 0 0 0 2-2c0-1.1.9-2 2-2h3.17\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M11 21.95V18a2 2 0 0 0-2-2a2 2 0 0 1-2-2v-1a2 2 0 0 0-2-2H2.05\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("ferris-wheel", "FerrisWheel", new string[] { "big wheel", "daisy wheel", "observation", "attraction", "entertainment", "amusement park", "theme park", "funfair" }, new string[] { "Navigation & Places" }, "<circle cx=\"12\" cy=\"12\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m6.8 15-3.5 2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20.7 7-3.5 2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6.8 9 3.3 7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20.7 17-3.5-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9 22 3-8 3 8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 22h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 18.7a9 9 0 1 0-12 0\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("footprints", "Footprints", new string[] { "steps", "walking", "foot", "feet", "trail", "shoe" }, new string[] { "Navigation & Places" }, "<path d=\"M4 16v-2.38C4 11.5 2.97 10.5 3 8c.03-2.72 1.49-6 4.5-6C9.37 2 10 3.8 10 5.5c0 3.11-2 5.66-2 8.68V16a2 2 0 1 1-4 0Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20 20v-2.38c0-2.12 1.03-3.12 1-5.62-.03-2.72-1.49-6-4.5-6C14.63 6 14 7.8 14 9.5c0 3.11 2 5.66 2 8.68V20a2 2 0 1 0 4 0Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 17h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4 13h4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("gavel", "Gavel", new string[] { "justice", "law", "court", "judgment", "legal", "hands", "penalty", "decision", "authority", "hammer", "mallet" }, new string[] { "Navigation & Places", "Tools" }, "<path d=\"m14 13-8.381 8.38a1 1 0 0 1-3.001-3l8.384-8.381\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16 16 6-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21.5 10.5-8-8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8 8 6-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8.5 7.5 8 8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("globe", "Globe", new string[] { "world", "browser", "language", "translate" }, new string[] { "Navigation & Places" }, "<circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 12h20\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("globe-check", "GlobeCheck", new string[] { "world", "browser", "language", "translate", "internet", "web", "check", "verified", "success", "valid", "available", "online", "status" }, new string[] { "Navigation & Places" }, "<path d=\"m15 6 2 2 4-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 12h20A10 10 0 1 1 12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 4-10\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("globe-off", "GlobeOff", new string[] { "globe", "earth", "planet", "disable", "mute", "off", "hide", "avoid", "world", "browser", "language", "translate", "internet", "offline", "disconnected", "network", "connection", "no connection", "network failure", "signal off" }, new string[] { "Navigation & Places", "Connectivity", "Devices" }, "<path d=\"M10.114 4.462A14.5 14.5 0 0 1 12 2a10 10 0 0 1 9.313 13.643\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15.557 15.556A14.5 14.5 0 0 1 12 22 10 10 0 0 1 4.929 4.929\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15.892 10.234A14.5 14.5 0 0 0 12 2a10 10 0 0 0-3.643.687\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.656 12H22\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19.071 19.071A10 10 0 0 1 12 22 14.5 14.5 0 0 1 8.44 8.45\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 12h10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("locate", "Locate", new string[] { "map", "gps", "location", "cross" }, new string[] { "Navigation & Places" }, "<line x1=\"2\" x2=\"5\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"19\" x2=\"22\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"12\" x2=\"12\" y1=\"2\" y2=\"5\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"12\" x2=\"12\" y1=\"19\" y2=\"22\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"7\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("locate-fixed", "LocateFixed", new string[] { "map", "gps", "location", "cross" }, new string[] { "Navigation & Places" }, "<line x1=\"2\" x2=\"5\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"19\" x2=\"22\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"12\" x2=\"12\" y1=\"2\" y2=\"5\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"12\" x2=\"12\" y1=\"19\" y2=\"22\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"7\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("locate-off", "LocateOff", new string[] { "map", "gps", "location", "cross" }, new string[] { "Navigation & Places" }, "<path d=\"M12 19v3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2v3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18.89 13.24a7 7 0 0 0-8.13-8.13\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 12h3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 12h3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7.05 7.05a7 7 0 0 0 9.9 9.9\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-minus", "MapMinus", new string[] { "location", "navigation", "travel", "drop", "delete", "remove", "erase" }, new string[] { "Navigation & Places", "Travel" }, "<path d=\"m11 19-1.106-.552a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0l4.212 2.106a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619V14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 5.764V14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 18h-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 3.236v15\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin", "MapPin", new string[] { "location", "waypoint", "marker", "drop" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-check", "MapPinCheck", new string[] { "location", "waypoint", "marker", "drop", "done", "tick", "complete", "task", "added" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M19.43 12.935c.357-.967.57-1.955.57-2.935a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0 32.197 32.197 0 0 0 .813-.728\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16 18 2 2 4-4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-check-inside", "MapPinCheckInside", new string[] { "location", "waypoint", "marker", "drop", "done", "tick", "complete", "task", "added" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9 10 2 2 4-4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-house", "MapPinHouse", new string[] { "location", "waypoint", "marker", "drop", "home", "living", "building", "residence", "architecture", "address", "poi", "real estate", "property", "navigation", "destination", "geolocation", "place", "landmark" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M15 22a1 1 0 0 1-1-1v-4a1 1 0 0 1 .445-.832l3-2a1 1 0 0 1 1.11 0l3 2A1 1 0 0 1 22 17v4a1 1 0 0 1-1 1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 10a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 .601.2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 22v-3\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"10\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-minus", "MapPinMinus", new string[] { "location", "waypoint", "marker", "drop", "delete", "remove", "erase" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M18.977 14C19.6 12.701 20 11.343 20 10a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0 32 32 0 0 0 .824-.738\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 18h6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-minus-inside", "MapPinMinusInside", new string[] { "location", "waypoint", "marker", "drop", "delete", "remove", "erase" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 10h6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-off", "MapPinOff", new string[] { "location", "waypoint", "marker", "remove" }, new string[] { "Navigation & Places", "Travel" }, "<path d=\"M12.75 7.09a3 3 0 0 1 2.16 2.16\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.072 17.072c-1.634 2.17-3.527 3.912-4.471 4.727a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 1.432-4.568\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.475 2.818A8 8 0 0 1 20 10c0 1.183-.31 2.377-.81 3.533\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.13 9.13a3 3 0 0 0 3.74 3.74\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-pen", "MapPinPen", new string[] { "location", "waypoint", "marker", "drop", "edit" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M17.97 9.304A8 8 0 0 0 2 10c0 4.69 4.887 9.562 7.022 11.468\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21.378 16.626a1 1 0 0 0-3.004-3.004l-4.01 4.012a2 2 0 0 0-.506.854l-.837 2.87a.5.5 0 0 0 .62.62l2.87-.837a2 2 0 0 0 .854-.506z\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"10\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-plus", "MapPinPlus", new string[] { "location", "waypoint", "marker", "drop", "add", "create", "new" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M19.914 11.105A7.298 7.298 0 0 0 20 10a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0 32 32 0 0 0 .824-.738\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 18h6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 15v6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-plus-inside", "MapPinPlusInside", new string[] { "location", "waypoint", "marker", "drop", "add", "create", "new" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 7v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 10h6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-x", "MapPinX", new string[] { "location", "waypoint", "marker", "drop", "delete", "remove", "erase" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M19.752 11.901A7.78 7.78 0 0 0 20 10a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0 19 19 0 0 0 .09-.077\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"10\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21.5 15.5-5 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21.5 20.5-5-5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pin-x-inside", "MapPinXInside", new string[] { "location", "waypoint", "marker", "drop", "delete", "remove", "erase" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14.5 7.5-5 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9.5 7.5 5 5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-pinned", "MapPinned", new string[] { "location", "waypoint", "marker", "drop" }, new string[] { "Navigation & Places", "Travel", "Account" }, "<path d=\"M18 8c0 3.613-3.869 7.429-5.393 8.795a1 1 0 0 1-1.214 0C9.87 15.429 6 11.613 6 8a6 6 0 0 1 12 0\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"8\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.714 14h-3.71a1 1 0 0 0-.948.683l-2.004 6A1 1 0 0 0 3 22h18a1 1 0 0 0 .948-1.316l-2-6a1 1 0 0 0-.949-.684h-3.712\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("map-plus", "MapPlus", new string[] { "location", "navigation", "travel", "new", "add", "create" }, new string[] { "Navigation & Places" }, "<path d=\"m11 19-1.106-.552a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0l4.212 2.106a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619V12\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 5.764V12\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 15v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 18h-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 3.236v15\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("navigation", "Navigation", new string[] { "location", "travel" }, new string[] { "Navigation & Places" }, "<polygon points=\"3 11 22 2 13 21 11 13 3 11\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("navigation-2", "Navigation2", new string[] { "location", "travel" }, new string[] { "Navigation & Places" }, "<polygon points=\"12 2 19 21 12 17 5 21 12 2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("navigation-2-off", "Navigation2Off", new string[] { "location", "travel" }, new string[] { "Navigation & Places" }, "<path d=\"M9.31 9.31 5 21l7-4 7 4-1.17-3.17\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14.53 8.88 12 2l-1.17 3.17\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("navigation-off", "NavigationOff", new string[] { "location", "travel" }, new string[] { "Navigation & Places" }, "<path d=\"M8.43 8.43 3 11l8 2 2 8 2.57-5.43\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.39 11.73 22 2l-9.73 4.61\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("pin", "Pin", new string[] { "save", "map", "lock", "fix" }, new string[] { "Navigation & Places", "Account" }, "<path d=\"M12 17v5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("pin-off", "PinOff", new string[] { "unpin", "map", "unlock", "unfix", "unsave", "remove" }, new string[] { "Navigation & Places" }, "<path d=\"M12 17v5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 9.34V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H7.89\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("radar", "Radar", new string[] { "scan", "sonar", "detect", "find", "locate" }, new string[] { "Navigation & Places", "Security", "Communication" }, "<path d=\"M19.07 4.93A10 10 0 0 0 6.99 3.34\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4 6h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2.29 9.62A10 10 0 1 0 21.31 8.35\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16.24 7.76A6 6 0 1 0 8.23 16.67\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 18h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.99 11.66A6 6 0 0 1 15.77 16.67\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m13.41 10.59 5.66-5.66\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("roller-coaster", "RollerCoaster", new string[] { "attraction", "entertainment", "amusement park", "theme park", "funfair" }, new string[] { "Navigation & Places" }, "<path d=\"M6 19V5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 19V6.8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 19v-7.8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 5v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 19v-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 19V9\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 19V9a4 4 0 0 1 4-4c2 0 4 1.33 6 4s4 4 6 4a4 4 0 1 0-3-6.65\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("route", "Route", new string[] { "path", "journey", "planner", "points", "stops", "stations" }, new string[] { "Navigation & Places" }, "<circle cx=\"6\" cy=\"19\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 19h8.5a3.5 3.5 0 0 0 0-7h-11a3.5 3.5 0 0 1 0-7H15\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"18\" cy=\"5\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("route-off", "RouteOff", new string[] { "path", "journey", "planner", "points", "stops", "stations", "reset", "clear", "cancelled", "closed", "blocked" }, new string[] { "Navigation & Places" }, "<circle cx=\"6\" cy=\"19\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 19h8.5c.4 0 .9-.1 1.3-.2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5.2 5.2A3.5 3.53 0 0 0 6.5 12H12\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 15.3a3.5 3.5 0 0 0-3.3-3.3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 5h-4.3\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"18\" cy=\"5\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scale", "Scale", new string[] { "balance", "legal", "license", "right", "rule", "law", "justice", "weight", "measure", "compare", "judge", "fair", "ethics", "decision" }, new string[] { "Navigation & Places", "Science", "Finance" }, "<path d=\"M12 3v18\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m19 8 3 8a5 5 0 0 1-6 0zV7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 7h1a17 17 0 0 0 8-2 17 17 0 0 0 8 2h1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m5 8 3 8a5 5 0 0 1-6 0zV7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 21h10\" xmlns=\"http://www.w3.org/2000/svg\" />"),
        };
    }

    internal static void RegisterNavigationAndPlaces(Dictionary<string, Type> registry, List<LucideIconModel> allIcons)
    {
        registry["binoculars"] = typeof(LucideBinoculars);
        registry["Binoculars"] = typeof(LucideBinoculars);
        registry["compass"] = typeof(LucideCompass);
        registry["Compass"] = typeof(LucideCompass);
        registry["dumbbell"] = typeof(LucideDumbbell);
        registry["Dumbbell"] = typeof(LucideDumbbell);
        registry["earth"] = typeof(LucideEarth);
        registry["Earth"] = typeof(LucideEarth);
        registry["ferris-wheel"] = typeof(LucideFerrisWheel);
        registry["FerrisWheel"] = typeof(LucideFerrisWheel);
        registry["footprints"] = typeof(LucideFootprints);
        registry["Footprints"] = typeof(LucideFootprints);
        registry["gavel"] = typeof(LucideGavel);
        registry["Gavel"] = typeof(LucideGavel);
        registry["globe"] = typeof(LucideGlobe);
        registry["Globe"] = typeof(LucideGlobe);
        registry["globe-check"] = typeof(LucideGlobeCheck);
        registry["GlobeCheck"] = typeof(LucideGlobeCheck);
        registry["globe-off"] = typeof(LucideGlobeOff);
        registry["GlobeOff"] = typeof(LucideGlobeOff);
        registry["locate"] = typeof(LucideLocate);
        registry["Locate"] = typeof(LucideLocate);
        registry["locate-fixed"] = typeof(LucideLocateFixed);
        registry["LocateFixed"] = typeof(LucideLocateFixed);
        registry["locate-off"] = typeof(LucideLocateOff);
        registry["LocateOff"] = typeof(LucideLocateOff);
        registry["map-minus"] = typeof(LucideMapMinus);
        registry["MapMinus"] = typeof(LucideMapMinus);
        registry["map-pin"] = typeof(LucideMapPin);
        registry["MapPin"] = typeof(LucideMapPin);
        registry["map-pin-check"] = typeof(LucideMapPinCheck);
        registry["MapPinCheck"] = typeof(LucideMapPinCheck);
        registry["map-pin-check-inside"] = typeof(LucideMapPinCheckInside);
        registry["MapPinCheckInside"] = typeof(LucideMapPinCheckInside);
        registry["map-pin-house"] = typeof(LucideMapPinHouse);
        registry["MapPinHouse"] = typeof(LucideMapPinHouse);
        registry["map-pin-minus"] = typeof(LucideMapPinMinus);
        registry["MapPinMinus"] = typeof(LucideMapPinMinus);
        registry["map-pin-minus-inside"] = typeof(LucideMapPinMinusInside);
        registry["MapPinMinusInside"] = typeof(LucideMapPinMinusInside);
        registry["map-pin-off"] = typeof(LucideMapPinOff);
        registry["MapPinOff"] = typeof(LucideMapPinOff);
        registry["map-pin-pen"] = typeof(LucideMapPinPen);
        registry["MapPinPen"] = typeof(LucideMapPinPen);
        registry["map-pin-plus"] = typeof(LucideMapPinPlus);
        registry["MapPinPlus"] = typeof(LucideMapPinPlus);
        registry["map-pin-plus-inside"] = typeof(LucideMapPinPlusInside);
        registry["MapPinPlusInside"] = typeof(LucideMapPinPlusInside);
        registry["map-pin-x"] = typeof(LucideMapPinX);
        registry["MapPinX"] = typeof(LucideMapPinX);
        registry["map-pin-x-inside"] = typeof(LucideMapPinXInside);
        registry["MapPinXInside"] = typeof(LucideMapPinXInside);
        registry["map-pinned"] = typeof(LucideMapPinned);
        registry["MapPinned"] = typeof(LucideMapPinned);
        registry["map-plus"] = typeof(LucideMapPlus);
        registry["MapPlus"] = typeof(LucideMapPlus);
        registry["navigation"] = typeof(LucideNavigation);
        registry["Navigation"] = typeof(LucideNavigation);
        registry["navigation-2"] = typeof(LucideNavigation2);
        registry["Navigation2"] = typeof(LucideNavigation2);
        registry["navigation-2-off"] = typeof(LucideNavigation2Off);
        registry["Navigation2Off"] = typeof(LucideNavigation2Off);
        registry["navigation-off"] = typeof(LucideNavigationOff);
        registry["NavigationOff"] = typeof(LucideNavigationOff);
        registry["pin"] = typeof(LucidePin);
        registry["Pin"] = typeof(LucidePin);
        registry["pin-off"] = typeof(LucidePinOff);
        registry["PinOff"] = typeof(LucidePinOff);
        registry["radar"] = typeof(LucideRadar);
        registry["Radar"] = typeof(LucideRadar);
        registry["roller-coaster"] = typeof(LucideRollerCoaster);
        registry["RollerCoaster"] = typeof(LucideRollerCoaster);
        registry["route"] = typeof(LucideRoute);
        registry["Route"] = typeof(LucideRoute);
        registry["route-off"] = typeof(LucideRouteOff);
        registry["RouteOff"] = typeof(LucideRouteOff);
        registry["scale"] = typeof(LucideScale);
        registry["Scale"] = typeof(LucideScale);
        allIcons.AddRange(NavigationAndPlacesIcons);
    }
}
