// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public static partial class LucideRegistry
{
    private static IReadOnlyList<LucideIconModel>? _gamingIcons;
    public static IReadOnlyList<LucideIconModel> GamingIcons => _gamingIcons ??= CreateGamingIcons();

    private static LucideIconModel[] CreateGamingIcons()
    {
        return new LucideIconModel[]
        {
            new("backpack", "Backpack", new string[] { "bag", "hiking", "travel", "camping", "school", "childhood" }, new string[] { "Gaming", "Photography", "Travel" }, "<path d=\"M4 10a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 10h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 18h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 22v-6a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 6V4a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("bow-arrow", "BowArrow", new string[] { "archer", "archery", "game", "war", "weapon" }, new string[] { "Gaming", "Tools" }, "<path d=\"M17 3h4v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18.575 11.082a13 13 0 0 1 1.048 9.027 1.17 1.17 0 0 1-1.914.597L14 17\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 10 3.29 6.29a1.17 1.17 0 0 1 .6-1.91 13 13 0 0 1 9.03 1.05\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 14a1.7 1.7 0 0 0-1.207.5l-2.646 2.646A.5.5 0 0 0 3.5 18H5a1 1 0 0 1 1 1v1.5a.5.5 0 0 0 .854.354L9.5 18.207A1.7 1.7 0 0 0 10 17v-2a1 1 0 0 0-1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.707 14.293 21 3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("chess-bishop", "ChessBishop", new string[] { "mitre", "miter", "piece", "board game", "religion" }, new string[] { "Gaming", "Emoji" }, "<path d=\"M5 20a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 18c1.5-.615 3-2.461 3-4.923C18 8.769 14.5 4.462 12 2 9.5 4.462 6 8.77 6 13.077 6 15.539 7.5 17.385 9 18\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16 7-2.5 2.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 2h6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("chess-king", "ChessKing", new string[] { "ruler", "crown", "piece", "board game", "stalemate" }, new string[] { "Gaming", "Emoji" }, "<path d=\"M4 20a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m6.7 18-1-1C4.35 15.682 3 14.09 3 12a5 5 0 0 1 4.95-5c1.584 0 2.7.455 4.05 1.818C13.35 7.455 14.466 7 16.05 7A5 5 0 0 1 21 12c0 2.082-1.359 3.673-2.7 5l-1 1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 4h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2v6.818\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("chess-knight", "ChessKnight", new string[] { "piece", "horse", "board game" }, new string[] { "Gaming", "Emoji" }, "<path d=\"M5 20a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16.5 18c1-2 2.5-5 2.5-9a7 7 0 0 0-7-7H6.635a1 1 0 0 0-.768 1.64L7 5l-2.32 5.802a2 2 0 0 0 .95 2.526l2.87 1.456\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m15 5 1.425-1.425\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17 8 1.53-1.53\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.713 12.185 7 18\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("chess-pawn", "ChessPawn", new string[] { "piece", "board game" }, new string[] { "Gaming", "Emoji" }, "<path d=\"M5 20a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14.5 10 1.5 8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 10h10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8 18 1.5-8\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"6\" r=\"4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("chess-queen", "ChessQueen", new string[] { "ruler", "crown", "piece", "board game", "stalemate" }, new string[] { "Gaming", "Emoji" }, "<path d=\"M4 20a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m12.474 5.943 1.567 5.34a1 1 0 0 0 1.75.328l2.616-3.402\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20 9-3 9\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m5.594 8.209 2.615 3.403a1 1 0 0 0 1.75-.329l1.567-5.34\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 18 4 9\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"4\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"20\" cy=\"7\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"4\" cy=\"7\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("chess-rook", "ChessRook", new string[] { "castle", "piece", "board game" }, new string[] { "Gaming", "Emoji" }, "<path d=\"M5 20a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17 18-1-9\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 2v5a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 4h12\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7 18 1-9\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("clover", "Clover", new string[] { "leaf", "luck", "plant" }, new string[] { "Gaming" }, "<path d=\"M16.17 7.83 2 22\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4.02 12a2.827 2.827 0 1 1 3.81-4.17A2.827 2.827 0 1 1 12 4.02a2.827 2.827 0 1 1 4.17 3.81A2.827 2.827 0 1 1 19.98 12a2.827 2.827 0 1 1-3.81 4.17A2.827 2.827 0 1 1 12 19.98a2.827 2.827 0 1 1-4.17-3.81A1 1 0 1 1 4 12\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7.83 7.83 8.34 8.34\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("coins", "Coins", new string[] { "money", "cash", "finance", "gamble" }, new string[] { "Gaming" }, "<path d=\"M13.744 17.736a6 6 0 1 1-7.48-7.48\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 6h1v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m6.134 14.768.866-.5 2 3.464\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"16\" cy=\"8\" r=\"6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("crown", "Crown", new string[] { "diadem", "tiara", "circlet", "corona", "king", "ruler", "winner", "favourite" }, new string[] { "Gaming" }, "<path d=\"M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 21h14\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dice-1", "Dice1", new string[] { "dice", "random", "tabletop", "1", "board", "game" }, new string[] { "Gaming" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 12h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dice-2", "Dice2", new string[] { "dice", "random", "tabletop", "2", "board", "game" }, new string[] { "Gaming" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 9h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 15h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dice-3", "Dice3", new string[] { "dice", "random", "tabletop", "3", "board", "game" }, new string[] { "Gaming" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 8h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 12h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 16h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dice-4", "Dice4", new string[] { "dice", "random", "tabletop", "4", "board", "game" }, new string[] { "Gaming" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 8h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 8h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 16h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 16h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dice-5", "Dice5", new string[] { "dice", "random", "tabletop", "5", "board", "game" }, new string[] { "Gaming" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 8h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 8h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 16h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 16h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 12h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dice-6", "Dice6", new string[] { "dice", "random", "tabletop", "6", "board", "game" }, new string[] { "Gaming" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 8h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 12h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 16h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 8h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 12h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 16h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dices", "Dices", new string[] { "dice", "random", "tabletop", "board", "game" }, new string[] { "Gaming" }, "<rect width=\"12\" height=\"12\" x=\"2\" y=\"10\" rx=\"2\" ry=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17.92 14 3.5-3.5a2.24 2.24 0 0 0 0-3l-5-4.92a2.24 2.24 0 0 0-3 0L10 6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 18h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 14h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 6h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 9h.01\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("gamepad", "Gamepad", new string[] { "console" }, new string[] { "Gaming", "Devices" }, "<line x1=\"6\" x2=\"10\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"8\" x2=\"8\" y1=\"10\" y2=\"14\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"15\" x2=\"15.01\" y1=\"13\" y2=\"13\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"18\" x2=\"18.01\" y1=\"11\" y2=\"11\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"20\" height=\"12\" x=\"2\" y=\"6\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("gamepad-2", "Gamepad2", new string[] { "console" }, new string[] { "Gaming", "Devices" }, "<line x1=\"6\" x2=\"10\" y1=\"11\" y2=\"11\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"8\" x2=\"8\" y1=\"9\" y2=\"13\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"15\" x2=\"15.01\" y1=\"12\" y2=\"12\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"18\" x2=\"18.01\" y1=\"10\" y2=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("gamepad-directional", "GamepadDirectional", new string[] { "direction", "arrow", "controller", "navigation", "button", "move", "pointer", "arrowhead", "console", "game", "gaming" }, new string[] { "Gaming", "Devices" }, "<path d=\"M11.146 15.854a1.207 1.207 0 0 1 1.708 0l1.56 1.56A2 2 0 0 1 15 18.828V21a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1v-2.172a2 2 0 0 1 .586-1.414z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18.828 15a2 2 0 0 1-1.414-.586l-1.56-1.56a1.207 1.207 0 0 1 0-1.708l1.56-1.56A2 2 0 0 1 18.828 9H21a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6.586 14.414A2 2 0 0 1 5.172 15H3a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1h2.172a2 2 0 0 1 1.414.586l1.56 1.56a1.207 1.207 0 0 1 0 1.708z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 3a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2.172a2 2 0 0 1-.586 1.414l-1.56 1.56a1.207 1.207 0 0 1-1.708 0l-1.56-1.56A2 2 0 0 1 9 5.172z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("gem", "Gem", new string[] { "diamond", "crystal", "ruby", "jewellery", "price", "special", "present", "gift", "ring", "wedding", "proposal", "marriage", "rubygems" }, new string[] { "Gaming", "Development", "Finance" }, "<path d=\"M10.5 3 8 9l4 13 4-13-2.5-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3a2 2 0 0 1 1.6.8l3 4a2 2 0 0 1 .013 2.382l-7.99 10.986a2 2 0 0 1-3.247 0l-7.99-10.986A2 2 0 0 1 2.4 7.8l2.998-3.997A2 2 0 0 1 7 3z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 9h20\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("ghost", "Ghost", new string[] { "pac-man", "spooky" }, new string[] { "Gaming" }, "<path d=\"M9 10h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 10h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2a8 8 0 0 0-8 8v12l3-3 2.5 2.5L12 19l2.5 2.5L17 19l3 3V10a8 8 0 0 0-8-8z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("gift", "Gift", new string[] { "present", "box", "birthday", "party" }, new string[] { "Gaming", "Account" }, "<path d=\"M12 7v14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20 11v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7.5 7a1 1 0 0 1 0-5A4.8 8 0 0 1 12 7a4.8 8 0 0 1 4.5-5 1 1 0 0 1 0 5\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"3\" y=\"7\" width=\"18\" height=\"4\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("goal", "Goal", new string[] { "flag", "bullseye" }, new string[] { "Gaming" }, "<path d=\"M12 13V2l8 4-8 4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M20.561 10.222a9 9 0 1 1-12.55-5.29\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.002 9.997a5 5 0 1 0 8.9 2.02\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("joystick", "Joystick", new string[] { "game", "console", "control stick" }, new string[] { "Gaming", "Devices" }, "<path d=\"M21 17a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-2Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 15v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 15V9\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"6\" r=\"3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("rocket", "Rocket", new string[] { "release", "boost", "launch", "space", "version" }, new string[] { "Gaming", "Development" }, "<path d=\"M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scroll", "Scroll", new string[] { "paper", "log", "scripture", "document", "notes", "parchment", "list", "long", "script", "story", "code", "coding" }, new string[] { "Gaming", "Development", "Text formatting" }, "<path d=\"M19 17V5a2 2 0 0 0-2-2H4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h12a2 2 0 0 0 2-2v-1a1 1 0 0 0-1-1H11a1 1 0 0 0-1 1v1a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v2a1 1 0 0 0 1 1h3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scroll-text", "ScrollText", new string[] { "paper", "log", "scripture", "document", "notes", "parchment", "list", "long", "script", "story", "code", "coding" }, new string[] { "Gaming", "Development", "Text formatting" }, "<path d=\"M15 12h-5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 8h-5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 17V5a2 2 0 0 0-2-2H4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 21h12a2 2 0 0 0 2-2v-1a1 1 0 0 0-1-1H11a1 1 0 0 0-1 1v1a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v2a1 1 0 0 0 1 1h3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("skull", "Skull", new string[] { "death", "danger", "bone" }, new string[] { "Gaming" }, "<path d=\"m12.5 17-.5-1-.5 1h1z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 22a1 1 0 0 0 1-1v-1a2 2 0 0 0 1.56-3.25 8 8 0 1 0-11.12 0A2 2 0 0 0 8 20v1a1 1 0 0 0 1 1z\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"15\" cy=\"12\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"12\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("sword", "Sword", new string[] { "battle", "challenge", "game", "war", "weapon" }, new string[] { "Gaming", "Tools" }, "<path d=\"m11 19-6-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m5 21-2-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8 16-4 4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.5 17.5 21 6V3h-3L6.5 14.5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("swords", "Swords", new string[] { "battle", "challenge", "game", "war", "weapon" }, new string[] { "Gaming", "Tools" }, "<polyline points=\"14.5 17.5 3 6 3 3 6 3 17.5 14.5\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"13\" x2=\"19\" y1=\"19\" y2=\"13\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"16\" x2=\"20\" y1=\"16\" y2=\"20\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"19\" x2=\"21\" y1=\"21\" y2=\"19\" xmlns=\"http://www.w3.org/2000/svg\" /><polyline points=\"14.5 6.5 18 3 21 3 21 6 17.5 9.5\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"5\" x2=\"9\" y1=\"14\" y2=\"18\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"7\" x2=\"4\" y1=\"17\" y2=\"20\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"3\" x2=\"5\" y1=\"19\" y2=\"21\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("target", "Target", new string[] { "logo", "bullseye", "deadline", "projects", "overview", "work", "productivity" }, new string[] { "Gaming" }, "<circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"6\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("toy-brick", "ToyBrick", new string[] { "lego", "block", "addon", "plugin", "integration" }, new string[] { "Gaming", "Development" }, "<rect width=\"18\" height=\"12\" x=\"3\" y=\"8\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 8V5c0-.6-.4-1-1-1H6a1 1 0 0 0-1 1v3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 8V5c0-.6-.4-1-1-1h-3a1 1 0 0 0-1 1v3\" xmlns=\"http://www.w3.org/2000/svg\" />"),
        };
    }

    internal static void RegisterGaming(Dictionary<string, Type> registry, List<LucideIconModel> allIcons)
    {
        registry["backpack"] = typeof(LucideBackpack);
        registry["Backpack"] = typeof(LucideBackpack);
        registry["bow-arrow"] = typeof(LucideBowArrow);
        registry["BowArrow"] = typeof(LucideBowArrow);
        registry["chess-bishop"] = typeof(LucideChessBishop);
        registry["ChessBishop"] = typeof(LucideChessBishop);
        registry["chess-king"] = typeof(LucideChessKing);
        registry["ChessKing"] = typeof(LucideChessKing);
        registry["chess-knight"] = typeof(LucideChessKnight);
        registry["ChessKnight"] = typeof(LucideChessKnight);
        registry["chess-pawn"] = typeof(LucideChessPawn);
        registry["ChessPawn"] = typeof(LucideChessPawn);
        registry["chess-queen"] = typeof(LucideChessQueen);
        registry["ChessQueen"] = typeof(LucideChessQueen);
        registry["chess-rook"] = typeof(LucideChessRook);
        registry["ChessRook"] = typeof(LucideChessRook);
        registry["clover"] = typeof(LucideClover);
        registry["Clover"] = typeof(LucideClover);
        registry["coins"] = typeof(LucideCoins);
        registry["Coins"] = typeof(LucideCoins);
        registry["crown"] = typeof(LucideCrown);
        registry["Crown"] = typeof(LucideCrown);
        registry["dice-1"] = typeof(LucideDice1);
        registry["Dice1"] = typeof(LucideDice1);
        registry["dice-2"] = typeof(LucideDice2);
        registry["Dice2"] = typeof(LucideDice2);
        registry["dice-3"] = typeof(LucideDice3);
        registry["Dice3"] = typeof(LucideDice3);
        registry["dice-4"] = typeof(LucideDice4);
        registry["Dice4"] = typeof(LucideDice4);
        registry["dice-5"] = typeof(LucideDice5);
        registry["Dice5"] = typeof(LucideDice5);
        registry["dice-6"] = typeof(LucideDice6);
        registry["Dice6"] = typeof(LucideDice6);
        registry["dices"] = typeof(LucideDices);
        registry["Dices"] = typeof(LucideDices);
        registry["gamepad"] = typeof(LucideGamepad);
        registry["Gamepad"] = typeof(LucideGamepad);
        registry["gamepad-2"] = typeof(LucideGamepad2);
        registry["Gamepad2"] = typeof(LucideGamepad2);
        registry["gamepad-directional"] = typeof(LucideGamepadDirectional);
        registry["GamepadDirectional"] = typeof(LucideGamepadDirectional);
        registry["gem"] = typeof(LucideGem);
        registry["Gem"] = typeof(LucideGem);
        registry["ghost"] = typeof(LucideGhost);
        registry["Ghost"] = typeof(LucideGhost);
        registry["gift"] = typeof(LucideGift);
        registry["Gift"] = typeof(LucideGift);
        registry["goal"] = typeof(LucideGoal);
        registry["Goal"] = typeof(LucideGoal);
        registry["joystick"] = typeof(LucideJoystick);
        registry["Joystick"] = typeof(LucideJoystick);
        registry["rocket"] = typeof(LucideRocket);
        registry["Rocket"] = typeof(LucideRocket);
        registry["scroll"] = typeof(LucideScroll);
        registry["Scroll"] = typeof(LucideScroll);
        registry["scroll-text"] = typeof(LucideScrollText);
        registry["ScrollText"] = typeof(LucideScrollText);
        registry["skull"] = typeof(LucideSkull);
        registry["Skull"] = typeof(LucideSkull);
        registry["sword"] = typeof(LucideSword);
        registry["Sword"] = typeof(LucideSword);
        registry["swords"] = typeof(LucideSwords);
        registry["Swords"] = typeof(LucideSwords);
        registry["target"] = typeof(LucideTarget);
        registry["Target"] = typeof(LucideTarget);
        registry["toy-brick"] = typeof(LucideToyBrick);
        registry["ToyBrick"] = typeof(LucideToyBrick);
        allIcons.AddRange(GamingIcons);
    }
}
