// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public static partial class LucideRegistry
{
    private static IReadOnlyList<LucideIconModel>? _medicalIcons;
    public static IReadOnlyList<LucideIconModel> MedicalIcons => _medicalIcons ??= CreateMedicalIcons();

    private static LucideIconModel[] CreateMedicalIcons()
    {
        return new LucideIconModel[]
        {
            new("activity", "Activity", new string[] { "pulse", "action", "motion", "movement", "exercise", "fitness", "healthcare", "heart rate monitor", "vital signs", "vitals", "emergency room", "er", "intensive care", "hospital", "defibrillator", "earthquake", "siesmic", "magnitude", "richter scale", "aftershock", "tremor", "shockwave", "audio", "waveform", "synthesizer", "synthesiser", "music" }, new string[] { "Medical", "Account", "Social", "Science", "Multimedia" }, "<path d=\"M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("ambulance", "Ambulance", new string[] { "ambulance", "emergency", "medical", "vehicle", "siren", "healthcare", "transportation", "rescue", "urgent", "first aid" }, new string[] { "Medical", "Transportation" }, "<path d=\"M10 10H6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19 18h2a1 1 0 0 0 1-1v-3.28a1 1 0 0 0-.684-.948l-1.923-.641a1 1 0 0 1-.578-.502l-1.539-3.076A1 1 0 0 0 16.382 8H14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 8v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 18h6\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"17\" cy=\"18\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"7\" cy=\"18\" r=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("bandage", "Bandage", new string[] { "plaster", "band-aid", "first aid", "medical", "health", "wound", "injury", "care", "treatment", "healing", "protection", "emergency", "aid", "safety", "patch" }, new string[] { "Medical" }, "<path d=\"M10 10.01h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 14.01h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 10.01h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 14.01h.01\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 6v12\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 6v12\" xmlns=\"http://www.w3.org/2000/svg\" /><rect x=\"2\" y=\"6\" width=\"20\" height=\"12\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("bone-fracture", "BoneFracture", new string[] { "bone", "fracture", "injury", "orthopedic", "medical", "anatomy", "skeletal", "broken", "xray", "trauma", "health", "vet", "veterinary", "crack", "break", "damage" }, new string[] { "Medical", "Animals" }, "<path d=\"M14 4.5a1 1 0 0 1 5 0 .5.5 0 0 0 .5.5 1 1 0 0 1 0 5c-.81 0-1.8-.7-2.5 0l-1.958 1.957a.15.15 0 0 1-.252-.072l-.493-2.07a.15.15 0 0 0-.111-.112l-2.072-.494a.15.15 0 0 1-.072-.252L14 7c.7-.7 0-1.69 0-2.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16 20-1-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20 16-2-1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m4 8 2 1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8 4 1 2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9.698 14.19a.15.15 0 0 0 .112.112l2.074.489a.15.15 0 0 1 .072.252L10 17c-.7.7 0 1.69 0 2.5a1 1 0 0 1-5 0 .495.495 0 0 0-.5-.5 1 1 0 0 1 0-5c.81 0 1.8.7 2.5 0l1.956-1.957a.15.15 0 0 1 .252.072z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("brain", "Brain", new string[] { "medical", "mind", "mental", "intellect", "cerebral", "consciousness", "genius", "artificial intelligence", "ai", "think", "thought", "insight", "intelligent", "smart" }, new string[] { "Medical", "Science" }, "<path d=\"M12 18V5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17.997 5.125a4 4 0 0 1 2.526 5.77\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 18a4 4 0 0 0 2-7.464\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 18a4 4 0 0 1-2-7.464\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6.003 5.125a4 4 0 0 0-2.526 5.77\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("briefcase-medical", "BriefcaseMedical", new string[] { "doctor", "medicine", "first aid" }, new string[] { "Medical", "Transportation" }, "<path d=\"M12 11v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 13h-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 6V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 6v14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 6v14\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"20\" height=\"14\" x=\"2\" y=\"6\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dna", "Dna", new string[] { "gene", "gmo", "helix", "heredity", "chromosome", "nucleic acid" }, new string[] { "Medical" }, "<path d=\"m10 16 1.5 1.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m14 8-1.5-1.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 2c-1.798 1.998-2.518 3.995-2.807 5.993\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m16.5 10.5 1 1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17 6-2.891-2.891\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 15c6.667-6 13.333 0 20-6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20 9 .891.891\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3.109 14.109 4 15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m6.5 12.5 1 1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7 18 2.891 2.891\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 22c1.798-1.998 2.518-3.995 2.807-5.993\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("dna-off", "DnaOff", new string[] { "gene", "gmo free", "helix", "heredity", "chromosome", "nucleic acid" }, new string[] { "Medical", "Food & beverage" }, "<path d=\"M15 2c-1.35 1.5-2.092 3-2.5 4.5L14 8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m17 6-2.891-2.891\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 15c3.333-3 6.667-3 10-3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 20 20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m20 9 .891.891\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M22 9c-1.5 1.35-3 2.092-4.5 2.5l-1-1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3.109 14.109 4 15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m6.5 12.5 1 1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m7 18 2.891 2.891\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 22c1.35-1.5 2.092-3 2.5-4.5L10 16\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("ear", "Ear", new string[] { "hearing", "noise", "audio", "accessibility" }, new string[] { "Medical", "Accessibility" }, "<path d=\"M6 8.5a6.5 6.5 0 1 1 13 0c0 6-6 6-6 10a3.5 3.5 0 1 1-7 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 8.5a2.5 2.5 0 0 0-5 0v1a2 2 0 1 1 0 4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("ear-off", "EarOff", new string[] { "hearing", "hard of hearing", "hearing loss", "deafness", "noise", "silence", "audio", "accessibility" }, new string[] { "Medical", "Accessibility" }, "<path d=\"M6 18.5a3.5 3.5 0 1 0 7 0c0-1.57.92-2.52 2.04-3.46\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 8.5c0-.75.13-1.47.36-2.14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8.8 3.15A6.5 6.5 0 0 1 19 8.5c0 1.63-.44 2.81-1.09 3.76\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12.5 6A2.5 2.5 0 0 1 15 8.5M10 13a2 2 0 0 0 1.82-1.18\" xmlns=\"http://www.w3.org/2000/svg\" /><line x1=\"2\" x2=\"22\" y1=\"2\" y2=\"22\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("heart", "Heart", new string[] { "like", "love", "emotion", "suit", "playing", "cards" }, new string[] { "Medical", "Social", "Multimedia", "Emoji", "Gaming", "Shapes" }, "<path d=\"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("heart-minus", "HeartMinus", new string[] { "unlike", "unfavorite", "remove", "delete", "damage" }, new string[] { "Medical", "Account", "Multimedia", "Gaming", "Social" }, "<path d=\"m14.876 18.99-1.368 1.323a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5a5.2 5.2 0 0 1-.244 1.572\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 15h6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("heart-plus", "HeartPlus", new string[] { "plus", "like", "favorite", "add", "health", "support" }, new string[] { "Medical", "Account", "Multimedia", "Gaming", "Social" }, "<path d=\"m14.479 19.374-.971.939a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5a5.2 5.2 0 0 1-.219 1.49\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 15h6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 12v6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("heart-pulse", "HeartPulse", new string[] { "heartbeat", "pulse", "health", "medical", "blood pressure", "cardiac", "systole", "diastole" }, new string[] { "Medical" }, "<path d=\"M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3.22 13H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("hospital", "Hospital", new string[] { "infirmary", "sanatorium", "healthcare", "doctor", "hospice", "clinic", "emergency room", "ward", "building", "medical", "vet" }, new string[] { "Medical", "Buildings", "Navigation & Places", "Travel" }, "<path d=\"M12 7v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 21v-3a2 2 0 0 0-4 0v3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 9h-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 11h2a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 21V5a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v16\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("mars", "Mars", new string[] { "gender", "sex", "male", "masculine", "man", "boy" }, new string[] { "Medical" }, "<path d=\"M16 3h5v5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 3-6.75 6.75\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"10\" cy=\"14\" r=\"6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("mars-stroke", "MarsStroke", new string[] { "gender", "androgyne", "transgender" }, new string[] { "Medical" }, "<path d=\"m14 6 4 4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3h4v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 3-7.75 7.75\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"9\" cy=\"15\" r=\"6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("non-binary", "NonBinary", new string[] { "gender", "nonbinary", "enby" }, new string[] { "Medical" }, "<path d=\"M12 2v10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8.5 4 7 4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8.5 8 7-4\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"17\" r=\"5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("pill", "Pill", new string[] { "medicine", "medication", "drug", "prescription", "tablet", "pharmacy" }, new string[] { "Medical" }, "<path d=\"m10.5 20.5 10-10a4.95 4.95 0 1 0-7-7l-10 10a4.95 4.95 0 1 0 7 7Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m8.5 8.5 7 7\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("pill-bottle", "PillBottle", new string[] { "medicine", "medication", "prescription", "drug", "supplement", "vitamin", "capsule", "jar", "container", "healthcare", "pharmaceutical", "tablet" }, new string[] { "Medical" }, "<path d=\"M18 11h-4a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M6 7v13a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7\" xmlns=\"http://www.w3.org/2000/svg\" /><rect width=\"16\" height=\"5\" x=\"4\" y=\"2\" rx=\"1\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scan-heart", "ScanHeart", new string[] { "health", "heart rate", "pulse", "monitoring", "healthiness", "screening", "dashed" }, new string[] { "Medical" }, "<path d=\"M17 3h2a2 2 0 0 1 2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3 7V5a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7.828 13.07A3 3 0 0 1 12 8.764a3 3 0 0 1 4.172 4.306l-3.447 3.62a1 1 0 0 1-1.449 0z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("siren", "Siren", new string[] { "police", "ambulance", "emergency", "security", "alert", "alarm", "light" }, new string[] { "Medical" }, "<path d=\"M7 18v-6a5 5 0 1 1 10 0v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M5 21a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1a2 2 0 0 0-2-2H7a2 2 0 0 0-2 2z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 12h1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18.5 4.5 18 5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 12h1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 2v1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m4.929 4.929.707.707\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 12v6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("square-activity", "SquareActivity", new string[] { "pulse", "action", "motion", "movement", "exercise", "fitness", "healthcare", "heart rate monitor", "vital signs", "vitals", "emergency room", "er", "intensive care", "hospital", "defibrillator", "earthquake", "siesmic", "magnitude", "richter scale", "aftershock", "tremor", "shockwave", "audio", "waveform", "synthesizer", "synthesiser", "music" }, new string[] { "Medical", "Social", "Science", "Multimedia" }, "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 12h-2l-2 5-2-10-2 5H7\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("tablets", "Tablets", new string[] { "medicine", "medication", "drug", "prescription", "pills", "pharmacy" }, new string[] { "Medical" }, "<circle cx=\"7\" cy=\"7\" r=\"5\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"17\" cy=\"17\" r=\"5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 17h10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m3.46 10.54 7.08-7.08\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("transgender", "Transgender", new string[] { "gender", "inclusive" }, new string[] { "Medical", "Accessibility" }, "<path d=\"M12 16v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M14 20h-4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M18 2h4v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m2 2 7.17 7.17\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 5.355V2h3.357\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m22 2-7.17 7.17\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 5 5 8\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("venus", "Venus", new string[] { "gender", "sex", "female", "feminine", "woman", "girl" }, new string[] { "Medical" }, "<path d=\"M12 15v7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 19h6\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"9\" r=\"6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("venus-and-mars", "VenusAndMars", new string[] { "gender", "sex", "intersex", "androgynous", "hermaphrodite" }, new string[] { "Medical" }, "<path d=\"M10 20h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 16v6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 2h4v4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m21 2-5.46 5.46\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"11\" r=\"5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
        };
    }

    internal static void RegisterMedical(Dictionary<string, Type> registry, List<LucideIconModel> allIcons)
    {
        registry["activity"] = typeof(LucideActivity);
        registry["Activity"] = typeof(LucideActivity);
        registry["ambulance"] = typeof(LucideAmbulance);
        registry["Ambulance"] = typeof(LucideAmbulance);
        registry["bandage"] = typeof(LucideBandage);
        registry["Bandage"] = typeof(LucideBandage);
        registry["bone-fracture"] = typeof(LucideBoneFracture);
        registry["BoneFracture"] = typeof(LucideBoneFracture);
        registry["brain"] = typeof(LucideBrain);
        registry["Brain"] = typeof(LucideBrain);
        registry["briefcase-medical"] = typeof(LucideBriefcaseMedical);
        registry["BriefcaseMedical"] = typeof(LucideBriefcaseMedical);
        registry["dna"] = typeof(LucideDna);
        registry["Dna"] = typeof(LucideDna);
        registry["dna-off"] = typeof(LucideDnaOff);
        registry["DnaOff"] = typeof(LucideDnaOff);
        registry["ear"] = typeof(LucideEar);
        registry["Ear"] = typeof(LucideEar);
        registry["ear-off"] = typeof(LucideEarOff);
        registry["EarOff"] = typeof(LucideEarOff);
        registry["heart"] = typeof(LucideHeart);
        registry["Heart"] = typeof(LucideHeart);
        registry["heart-minus"] = typeof(LucideHeartMinus);
        registry["HeartMinus"] = typeof(LucideHeartMinus);
        registry["heart-plus"] = typeof(LucideHeartPlus);
        registry["HeartPlus"] = typeof(LucideHeartPlus);
        registry["heart-pulse"] = typeof(LucideHeartPulse);
        registry["HeartPulse"] = typeof(LucideHeartPulse);
        registry["hospital"] = typeof(LucideHospital);
        registry["Hospital"] = typeof(LucideHospital);
        registry["mars"] = typeof(LucideMars);
        registry["Mars"] = typeof(LucideMars);
        registry["mars-stroke"] = typeof(LucideMarsStroke);
        registry["MarsStroke"] = typeof(LucideMarsStroke);
        registry["non-binary"] = typeof(LucideNonBinary);
        registry["NonBinary"] = typeof(LucideNonBinary);
        registry["pill"] = typeof(LucidePill);
        registry["Pill"] = typeof(LucidePill);
        registry["pill-bottle"] = typeof(LucidePillBottle);
        registry["PillBottle"] = typeof(LucidePillBottle);
        registry["scan-heart"] = typeof(LucideScanHeart);
        registry["ScanHeart"] = typeof(LucideScanHeart);
        registry["siren"] = typeof(LucideSiren);
        registry["Siren"] = typeof(LucideSiren);
        registry["square-activity"] = typeof(LucideSquareActivity);
        registry["SquareActivity"] = typeof(LucideSquareActivity);
        registry["tablets"] = typeof(LucideTablets);
        registry["Tablets"] = typeof(LucideTablets);
        registry["transgender"] = typeof(LucideTransgender);
        registry["Transgender"] = typeof(LucideTransgender);
        registry["venus"] = typeof(LucideVenus);
        registry["Venus"] = typeof(LucideVenus);
        registry["venus-and-mars"] = typeof(LucideVenusAndMars);
        registry["VenusAndMars"] = typeof(LucideVenusAndMars);
        allIcons.AddRange(MedicalIcons);
    }
}
