// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public static partial class LucideRegistry
{
    private static IReadOnlyList<LucideIconModel>? _shoppingIcons;
    public static IReadOnlyList<LucideIconModel> ShoppingIcons => _shoppingIcons ??= CreateShoppingIcons();

    private static LucideIconModel[] CreateShoppingIcons()
    {
        return new LucideIconModel[]
        {
            new("badge-cent", "BadgeCent", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "cents", "dollar", "usd", "$", "¢" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 7v10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15.4 10a4 4 0 1 0 0 4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-dollar-sign", "BadgeDollarSign", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "usd", "$" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 18V6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-euro", "BadgeEuro", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "€" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 12h5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M15 9.4a4 4 0 1 0 0 5.2\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-indian-rupee", "BadgeIndianRupee", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "inr", "₹" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 8h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 12h8\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m13 17-5-1h1a4 4 0 0 0 0-8\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-japanese-yen", "BadgeJapaneseYen", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "jpy", "¥" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9 8 3 3v7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m12 11 3-3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 12h6\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 16h6\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-pound-sterling", "BadgePoundSterling", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "british", "gbp", "£" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 12h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M10 16V9.5a2.5 2.5 0 0 1 5 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 16h7\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-russian-ruble", "BadgeRussianRuble", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "rub", "₽" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 16h5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 12h5a2 2 0 1 0 0-4h-3v9\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-swiss-franc", "BadgeSwissFranc", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "chf", "₣" }, new string[] { "Shopping", "Finance" }, "<path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M11 17V8h4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M11 12h3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M9 16h4\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("badge-turkish-lira", "BadgeTurkishLira", new string[] { "discount", "offer", "sale", "voucher", "tag", "monetization", "marketing", "finance", "financial", "exchange", "transaction", "payment", "try", "₺" }, new string[] { "Shopping", "Finance" }, "<path d=\"M11 7v10a5 5 0 0 0 5-5\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m15 8-6 3\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("barcode", "Barcode", new string[] { "scan", "checkout", "till", "cart", "transaction", "purchase", "buy", "product", "packaging", "retail", "consumer" }, new string[] { "Shopping" }, "<path d=\"M3 5v14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 5v14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 5v14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 5v14\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 5v14\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("circle-euro", "CircleEuro", new string[] { "symbol", "economy", "banking", "europe", "€", "euro", "currency", "money", "payment", "coin", "finance", "financial", "exchange" }, new string[] { "Shopping", "Finance" }, "<path d=\"M15 9.4a4 4 0 1 0 0 5.2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 12h5\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"12\" cy=\"12\" r=\"10\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("handbag", "Handbag", new string[] { "bag", "baggage", "carry", "clutch", "fashion", "luggage", "purse", "tote", "travel" }, new string[] { "Shopping", "Transportation" }, "<path d=\"M2.048 18.566A2 2 0 0 0 4 21h16a2 2 0 0 0 1.952-2.434l-2-9A2 2 0 0 0 18 8H6a2 2 0 0 0-1.952 1.566z\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 11V6a4 4 0 0 1 8 0v5\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("scan-barcode", "ScanBarcode", new string[] { "checkout", "till", "cart", "transaction", "purchase", "buy", "product", "packaging", "retail", "consumer" }, new string[] { "Shopping", "Devices" }, "<path d=\"M3 7V5a2 2 0 0 1 2-2h2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M8 7v10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M12 7v10\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M17 7v10\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("shirt", "Shirt", new string[] { "t-shirt", "shopping", "store", "clothing", "clothes" }, new string[] { "Shopping" }, "<path d=\"M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("shopping-bag", "ShoppingBag", new string[] { "ecommerce", "cart", "purchase", "store" }, new string[] { "Shopping" }, "<path d=\"M16 10a4 4 0 0 1-8 0\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3.103 6.034h17.794\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M3.4 5.467a2 2 0 0 0-.4 1.2V20a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6.667a2 2 0 0 0-.4-1.2l-2-2.667A2 2 0 0 0 17 2H7a2 2 0 0 0-1.6.8z\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("shopping-basket", "ShoppingBasket", new string[] { "cart", "e-commerce", "store", "purchase", "products", "items", "ingredients" }, new string[] { "Shopping" }, "<path d=\"m15 11-1 9\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m19 11-4-7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2 11h20\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m3.5 11 1.6 7.4a2 2 0 0 0 2 1.6h9.8a2 2 0 0 0 2-1.6l1.7-7.4\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M4.5 15.5h15\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m5 11 4-7\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"m9 11 1 9\" xmlns=\"http://www.w3.org/2000/svg\" />"),
            new("shopping-cart", "ShoppingCart", new string[] { "trolley", "cart", "basket", "e-commerce", "store", "purchase", "products", "items", "ingredients" }, new string[] { "Shopping" }, "<circle cx=\"8\" cy=\"21\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" /><circle cx=\"19\" cy=\"21\" r=\"1\" xmlns=\"http://www.w3.org/2000/svg\" /><path d=\"M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12\" xmlns=\"http://www.w3.org/2000/svg\" />"),
        };
    }

    internal static void RegisterShopping(Dictionary<string, Type> registry, List<LucideIconModel> allIcons)
    {
        registry["badge-cent"] = typeof(LucideBadgeCent);
        registry["BadgeCent"] = typeof(LucideBadgeCent);
        registry["badge-dollar-sign"] = typeof(LucideBadgeDollarSign);
        registry["BadgeDollarSign"] = typeof(LucideBadgeDollarSign);
        registry["badge-euro"] = typeof(LucideBadgeEuro);
        registry["BadgeEuro"] = typeof(LucideBadgeEuro);
        registry["badge-indian-rupee"] = typeof(LucideBadgeIndianRupee);
        registry["BadgeIndianRupee"] = typeof(LucideBadgeIndianRupee);
        registry["badge-japanese-yen"] = typeof(LucideBadgeJapaneseYen);
        registry["BadgeJapaneseYen"] = typeof(LucideBadgeJapaneseYen);
        registry["badge-pound-sterling"] = typeof(LucideBadgePoundSterling);
        registry["BadgePoundSterling"] = typeof(LucideBadgePoundSterling);
        registry["badge-russian-ruble"] = typeof(LucideBadgeRussianRuble);
        registry["BadgeRussianRuble"] = typeof(LucideBadgeRussianRuble);
        registry["badge-swiss-franc"] = typeof(LucideBadgeSwissFranc);
        registry["BadgeSwissFranc"] = typeof(LucideBadgeSwissFranc);
        registry["badge-turkish-lira"] = typeof(LucideBadgeTurkishLira);
        registry["BadgeTurkishLira"] = typeof(LucideBadgeTurkishLira);
        registry["barcode"] = typeof(LucideBarcode);
        registry["Barcode"] = typeof(LucideBarcode);
        registry["circle-euro"] = typeof(LucideCircleEuro);
        registry["CircleEuro"] = typeof(LucideCircleEuro);
        registry["handbag"] = typeof(LucideHandbag);
        registry["Handbag"] = typeof(LucideHandbag);
        registry["scan-barcode"] = typeof(LucideScanBarcode);
        registry["ScanBarcode"] = typeof(LucideScanBarcode);
        registry["shirt"] = typeof(LucideShirt);
        registry["Shirt"] = typeof(LucideShirt);
        registry["shopping-bag"] = typeof(LucideShoppingBag);
        registry["ShoppingBag"] = typeof(LucideShoppingBag);
        registry["shopping-basket"] = typeof(LucideShoppingBasket);
        registry["ShoppingBasket"] = typeof(LucideShoppingBasket);
        registry["shopping-cart"] = typeof(LucideShoppingCart);
        registry["ShoppingCart"] = typeof(LucideShoppingCart);
        allIcons.AddRange(ShoppingIcons);
    }
}
