<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Authors>ShadBlazor Team</Authors>
    <Company>ShadBlazor</Company>
    <RepositoryUrl>https://github.com/clight7664/ShadBlazor.Lucide</RepositoryUrl>
    <PackageProjectUrl>https://github.com/clight7664/ShadBlazor.Lucide</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
