// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideSheet : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "18");
        b.AddAttribute(s++, "height", "18");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.AddAttribute(s++, "ry", "2");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "3");
        b.AddAttribute(s++, "x2", "21");
        b.AddAttribute(s++, "y1", "9");
        b.AddAttribute(s++, "y2", "9");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "3");
        b.AddAttribute(s++, "x2", "21");
        b.AddAttribute(s++, "y1", "15");
        b.AddAttribute(s++, "y2", "15");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "9");
        b.AddAttribute(s++, "x2", "9");
        b.AddAttribute(s++, "y1", "9");
        b.AddAttribute(s++, "y2", "21");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "15");
        b.AddAttribute(s++, "x2", "15");
        b.AddAttribute(s++, "y1", "9");
        b.AddAttribute(s++, "y2", "21");
        b.CloseElement();
    }
}
