// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideAlignEndVertical : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "16");
        b.AddAttribute(s++, "height", "6");
        b.AddAttribute(s++, "x", "2");
        b.AddAttribute(s++, "y", "4");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "9");
        b.AddAttribute(s++, "height", "6");
        b.AddAttribute(s++, "x", "9");
        b.AddAttribute(s++, "y", "14");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M22 22V2");
        b.CloseElement();
    }
}
