// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideItalic : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "19");
        b.AddAttribute(s++, "x2", "10");
        b.AddAttribute(s++, "y1", "4");
        b.AddAttribute(s++, "y2", "4");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "14");
        b.AddAttribute(s++, "x2", "5");
        b.AddAttribute(s++, "y1", "20");
        b.AddAttribute(s++, "y2", "20");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "15");
        b.AddAttribute(s++, "x2", "9");
        b.AddAttribute(s++, "y1", "4");
        b.AddAttribute(s++, "y2", "20");
        b.CloseElement();
    }
}
