// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideClosedCaption : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M10 9.17a3 3 0 1 0 0 5.66");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M17 9.17a3 3 0 1 0 0 5.66");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "2");
        b.AddAttribute(s++, "y", "5");
        b.AddAttribute(s++, "width", "20");
        b.AddAttribute(s++, "height", "14");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
