// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideReplace : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M14 4a1 1 0 0 1 1-1");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M15 10a1 1 0 0 1-1-1");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M21 4a1 1 0 0 0-1-1");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M21 9a1 1 0 0 1-1 1");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m3 7 3 3 3-3");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M6 10V5a2 2 0 0 1 2-2h2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "14");
        b.AddAttribute(s++, "width", "7");
        b.AddAttribute(s++, "height", "7");
        b.AddAttribute(s++, "rx", "1");
        b.CloseElement();
    }
}
