// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideMailbox : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M22 17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.5C2 7 4 5 6.5 5H18c2.2 0 4 1.8 4 4v8Z");
        b.CloseElement();
        b.OpenElement(s++, "polyline");
        b.AddAttribute(s++, "points", "15,9 18,9 18,11");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M6.5 5C9 5 11 7 11 9.5V17a2 2 0 0 1-2 2");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "6");
        b.AddAttribute(s++, "x2", "7");
        b.AddAttribute(s++, "y1", "10");
        b.AddAttribute(s++, "y2", "10");
        b.CloseElement();
    }
}
