// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideBaggageClaim : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M22 18H6a2 2 0 0 1-2-2V7a2 2 0 0 0-2-2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M17 14V4a2 2 0 0 0-2-2h-1a2 2 0 0 0-2 2v10");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "13");
        b.AddAttribute(s++, "height", "8");
        b.AddAttribute(s++, "x", "8");
        b.AddAttribute(s++, "y", "6");
        b.AddAttribute(s++, "rx", "1");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "18");
        b.AddAttribute(s++, "cy", "20");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "9");
        b.AddAttribute(s++, "cy", "20");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
    }
}
