// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideGalleryHorizontalEnd : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M2 7v10");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M6 5v14");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "12");
        b.AddAttribute(s++, "height", "18");
        b.AddAttribute(s++, "x", "10");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
