// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideVibrateOff : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m2 8 2 2-2 2 2 2-2 2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m22 8-2 2 2 2-2 2 2 2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M8 8v10c0 .55.45 1 1 1h6c.55 0 1-.45 1-1v-2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M16 10.34V6c0-.55-.45-1-1-1h-4.34");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "2");
        b.AddAttribute(s++, "x2", "22");
        b.AddAttribute(s++, "y1", "2");
        b.AddAttribute(s++, "y2", "22");
        b.CloseElement();
    }
}
