// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideCirclePlay : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M9 9.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997A1 1 0 0 1 9 14.996z");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "10");
        b.CloseElement();
    }
}
