// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideCirclePile : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "19");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "5");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "16");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "20");
        b.AddAttribute(s++, "cy", "19");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "4");
        b.AddAttribute(s++, "cy", "19");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "8");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
    }
}
