// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideCopyPlus : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "15");
        b.AddAttribute(s++, "x2", "15");
        b.AddAttribute(s++, "y1", "12");
        b.AddAttribute(s++, "y2", "18");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "12");
        b.AddAttribute(s++, "x2", "18");
        b.AddAttribute(s++, "y1", "15");
        b.AddAttribute(s++, "y2", "15");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "14");
        b.AddAttribute(s++, "height", "14");
        b.AddAttribute(s++, "x", "8");
        b.AddAttribute(s++, "y", "8");
        b.AddAttribute(s++, "rx", "2");
        b.AddAttribute(s++, "ry", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2");
        b.CloseElement();
    }
}
