// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideDecimalsArrowLeft : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m13 21-3-3 3-3");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M20 18H10");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M3 11h.01");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "6");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "width", "5");
        b.AddAttribute(s++, "height", "8");
        b.AddAttribute(s++, "rx", "2.5");
        b.CloseElement();
    }
}
