// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideMicOff : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M12 19v3");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M15 9.34V5a3 3 0 0 0-5.68-1.33");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M16.95 16.95A7 7 0 0 1 5 12v-2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M18.89 13.23A7 7 0 0 0 19 12v-2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m2 2 20 20");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M9 9v3a3 3 0 0 0 5.12 2.12");
        b.CloseElement();
    }
}
