// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideAlignVerticalDistributeCenter : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M22 17h-3");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M22 7h-5");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M5 17H2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M7 7H2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "5");
        b.AddAttribute(s++, "y", "14");
        b.AddAttribute(s++, "width", "14");
        b.AddAttribute(s++, "height", "6");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "7");
        b.AddAttribute(s++, "y", "4");
        b.AddAttribute(s++, "width", "10");
        b.AddAttribute(s++, "height", "6");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
