// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideAirplay : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m12 15 5 6H7Z");
        b.CloseElement();
    }
}
