// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideSquareUserRound : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M18 21a6 6 0 0 0-12 0");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "11");
        b.AddAttribute(s++, "r", "4");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "18");
        b.AddAttribute(s++, "height", "18");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
