// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideWorkflow : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "8");
        b.AddAttribute(s++, "height", "8");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M7 11v4a2 2 0 0 0 2 2h4");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "8");
        b.AddAttribute(s++, "height", "8");
        b.AddAttribute(s++, "x", "13");
        b.AddAttribute(s++, "y", "13");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
