// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideBanknote : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "20");
        b.AddAttribute(s++, "height", "12");
        b.AddAttribute(s++, "x", "2");
        b.AddAttribute(s++, "y", "6");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M6 12h.01M18 12h.01");
        b.CloseElement();
    }
}
