// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideVault : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "18");
        b.AddAttribute(s++, "height", "18");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "7.5");
        b.AddAttribute(s++, "cy", "7.5");
        b.AddAttribute(s++, "r", ".5");
        b.AddAttribute(s++, "fill", "currentColor");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m7.9 7.9 2.7 2.7");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "16.5");
        b.AddAttribute(s++, "cy", "7.5");
        b.AddAttribute(s++, "r", ".5");
        b.AddAttribute(s++, "fill", "currentColor");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m13.4 10.6 2.7-2.7");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "7.5");
        b.AddAttribute(s++, "cy", "16.5");
        b.AddAttribute(s++, "r", ".5");
        b.AddAttribute(s++, "fill", "currentColor");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m7.9 16.1 2.7-2.7");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "16.5");
        b.AddAttribute(s++, "cy", "16.5");
        b.AddAttribute(s++, "r", ".5");
        b.AddAttribute(s++, "fill", "currentColor");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m13.4 13.4 2.7 2.7");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
    }
}
