// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideTurntable : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M10 12.01h.01");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M18 8v4a8 8 0 0 1-1.07 4");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "10");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "4");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "2");
        b.AddAttribute(s++, "y", "4");
        b.AddAttribute(s++, "width", "20");
        b.AddAttribute(s++, "height", "16");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
