// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideDivide : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "6");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "5");
        b.AddAttribute(s++, "x2", "19");
        b.AddAttribute(s++, "y1", "12");
        b.AddAttribute(s++, "y2", "12");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "18");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
    }
}
