// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideSquareArrowUp : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "18");
        b.AddAttribute(s++, "height", "18");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m16 12-4-4-4 4");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M12 16V8");
        b.CloseElement();
    }
}
