// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideAlbum : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "18");
        b.AddAttribute(s++, "height", "18");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.AddAttribute(s++, "ry", "2");
        b.CloseElement();
        b.OpenElement(s++, "polyline");
        b.AddAttribute(s++, "points", "11 3 11 11 14 8 17 11 17 3");
        b.CloseElement();
    }
}
