// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideMirrorRectangular : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M11 6 8 9");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m16 7-8 8");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "4");
        b.AddAttribute(s++, "y", "2");
        b.AddAttribute(s++, "width", "16");
        b.AddAttribute(s++, "height", "20");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
