// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideCassetteTape : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "20");
        b.AddAttribute(s++, "height", "16");
        b.AddAttribute(s++, "x", "2");
        b.AddAttribute(s++, "y", "4");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "8");
        b.AddAttribute(s++, "cy", "10");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M8 12h8");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "16");
        b.AddAttribute(s++, "cy", "10");
        b.AddAttribute(s++, "r", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m6 20 .7-2.9A1.4 1.4 0 0 1 8.1 16h7.8a1.4 1.4 0 0 1 1.4 1l.7 3");
        b.CloseElement();
    }
}
