// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideStretchVertical : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "6");
        b.AddAttribute(s++, "height", "20");
        b.AddAttribute(s++, "x", "4");
        b.AddAttribute(s++, "y", "2");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "6");
        b.AddAttribute(s++, "height", "20");
        b.AddAttribute(s++, "x", "14");
        b.AddAttribute(s++, "y", "2");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
