// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideLink2Off : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M9 17H7A5 5 0 0 1 7 7");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M15 7h2a5 5 0 0 1 4 8");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "8");
        b.AddAttribute(s++, "x2", "12");
        b.AddAttribute(s++, "y1", "12");
        b.AddAttribute(s++, "y2", "12");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "2");
        b.AddAttribute(s++, "x2", "22");
        b.AddAttribute(s++, "y1", "2");
        b.AddAttribute(s++, "y2", "22");
        b.CloseElement();
    }
}
