// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideGripVertical : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "9");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "9");
        b.AddAttribute(s++, "cy", "5");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "9");
        b.AddAttribute(s++, "cy", "19");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "15");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "15");
        b.AddAttribute(s++, "cy", "5");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "15");
        b.AddAttribute(s++, "cy", "19");
        b.AddAttribute(s++, "r", "1");
        b.CloseElement();
    }
}
