// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucidePauseCircle : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "10");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "10");
        b.AddAttribute(s++, "x2", "10");
        b.AddAttribute(s++, "y1", "15");
        b.AddAttribute(s++, "y2", "9");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "14");
        b.AddAttribute(s++, "x2", "14");
        b.AddAttribute(s++, "y1", "15");
        b.AddAttribute(s++, "y2", "9");
        b.CloseElement();
    }
}
