// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideGamepad2 : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "6");
        b.AddAttribute(s++, "x2", "10");
        b.AddAttribute(s++, "y1", "11");
        b.AddAttribute(s++, "y2", "11");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "8");
        b.AddAttribute(s++, "x2", "8");
        b.AddAttribute(s++, "y1", "9");
        b.AddAttribute(s++, "y2", "13");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "15");
        b.AddAttribute(s++, "x2", "15.01");
        b.AddAttribute(s++, "y1", "12");
        b.AddAttribute(s++, "y2", "12");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "18");
        b.AddAttribute(s++, "x2", "18.01");
        b.AddAttribute(s++, "y1", "10");
        b.AddAttribute(s++, "y2", "10");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z");
        b.CloseElement();
    }
}
