// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideCurrency : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "circle");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "12");
        b.AddAttribute(s++, "r", "8");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "3");
        b.AddAttribute(s++, "x2", "6");
        b.AddAttribute(s++, "y1", "3");
        b.AddAttribute(s++, "y2", "6");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "21");
        b.AddAttribute(s++, "x2", "18");
        b.AddAttribute(s++, "y1", "3");
        b.AddAttribute(s++, "y2", "6");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "3");
        b.AddAttribute(s++, "x2", "6");
        b.AddAttribute(s++, "y1", "21");
        b.AddAttribute(s++, "y2", "18");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "21");
        b.AddAttribute(s++, "x2", "18");
        b.AddAttribute(s++, "y1", "21");
        b.AddAttribute(s++, "y2", "18");
        b.CloseElement();
    }
}
