// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideBriefcaseBusiness : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M12 12h.01");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M16 6V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M22 13a18.15 18.15 0 0 1-20 0");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "20");
        b.AddAttribute(s++, "height", "14");
        b.AddAttribute(s++, "x", "2");
        b.AddAttribute(s++, "y", "6");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
