// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideZodiacVirgo : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M11 5.5a1 1 0 0 1 5 0V16a5 5 0 0 0 5 5");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M16 11.5a1 1 0 0 1 5 0V16a5 5 0 0 1-5 5");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M6 19V6a3 3 0 0 0-3-3h0");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M6 5.5a1 1 0 0 1 5 0V19");
        b.CloseElement();
    }
}
