// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideDatabaseCheck : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "m16 19 2 2 4-4");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M21 13.127V5");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M3 12A9 3 0 0 0 21 12");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M3 5V19A9 3 0 0 0 13.318 21.968");
        b.CloseElement();
        b.OpenElement(s++, "ellipse");
        b.AddAttribute(s++, "cx", "12");
        b.AddAttribute(s++, "cy", "5");
        b.AddAttribute(s++, "rx", "9");
        b.AddAttribute(s++, "ry", "3");
        b.CloseElement();
    }
}
