// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideStrikethrough : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M16 4H9a3 3 0 0 0-2.83 4");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M14 12a4 4 0 0 1 0 8H6");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "4");
        b.AddAttribute(s++, "x2", "20");
        b.AddAttribute(s++, "y1", "12");
        b.AddAttribute(s++, "y2", "12");
        b.CloseElement();
    }
}
