// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideAlignVerticalSpaceBetween : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "14");
        b.AddAttribute(s++, "height", "6");
        b.AddAttribute(s++, "x", "5");
        b.AddAttribute(s++, "y", "15");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "10");
        b.AddAttribute(s++, "height", "6");
        b.AddAttribute(s++, "x", "7");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M2 21h20");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M2 3h20");
        b.CloseElement();
    }
}
