// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideFrame : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "22");
        b.AddAttribute(s++, "x2", "2");
        b.AddAttribute(s++, "y1", "6");
        b.AddAttribute(s++, "y2", "6");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "22");
        b.AddAttribute(s++, "x2", "2");
        b.AddAttribute(s++, "y1", "18");
        b.AddAttribute(s++, "y2", "18");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "6");
        b.AddAttribute(s++, "x2", "6");
        b.AddAttribute(s++, "y1", "2");
        b.AddAttribute(s++, "y2", "22");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "18");
        b.AddAttribute(s++, "x2", "18");
        b.AddAttribute(s++, "y1", "2");
        b.AddAttribute(s++, "y2", "22");
        b.CloseElement();
    }
}
