// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideHome : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z");
        b.CloseElement();
    }
}
