// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideFullscreen : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M3 7V5a2 2 0 0 1 2-2h2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M17 3h2a2 2 0 0 1 2 2v2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M21 17v2a2 2 0 0 1-2 2h-2");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M7 21H5a2 2 0 0 1-2-2v-2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "width", "10");
        b.AddAttribute(s++, "height", "8");
        b.AddAttribute(s++, "x", "7");
        b.AddAttribute(s++, "y", "8");
        b.AddAttribute(s++, "rx", "1");
        b.CloseElement();
    }
}
