// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideImageOff : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "2");
        b.AddAttribute(s++, "x2", "22");
        b.AddAttribute(s++, "y1", "2");
        b.AddAttribute(s++, "y2", "22");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M10.41 10.41a2 2 0 1 1-2.83-2.83");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "13.5");
        b.AddAttribute(s++, "x2", "6");
        b.AddAttribute(s++, "y1", "13.5");
        b.AddAttribute(s++, "y2", "21");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "18");
        b.AddAttribute(s++, "x2", "21");
        b.AddAttribute(s++, "y1", "12");
        b.AddAttribute(s++, "y2", "15");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M21 15V5a2 2 0 0 0-2-2H9");
        b.CloseElement();
    }
}
