// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideEqual : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "5");
        b.AddAttribute(s++, "x2", "19");
        b.AddAttribute(s++, "y1", "9");
        b.AddAttribute(s++, "y2", "9");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "5");
        b.AddAttribute(s++, "x2", "19");
        b.AddAttribute(s++, "y1", "15");
        b.AddAttribute(s++, "y2", "15");
        b.CloseElement();
    }
}
