// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideUngroup : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "11");
        b.AddAttribute(s++, "y", "14");
        b.AddAttribute(s++, "width", "10");
        b.AddAttribute(s++, "height", "7");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "3");
        b.AddAttribute(s++, "y", "3");
        b.AddAttribute(s++, "width", "10");
        b.AddAttribute(s++, "height", "7");
        b.AddAttribute(s++, "rx", "2");
        b.CloseElement();
    }
}
