// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideHardHat : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M10 10V5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v5");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M14 6a6 6 0 0 1 6 6v3");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M4 15v-3a6 6 0 0 1 6-6");
        b.CloseElement();
        b.OpenElement(s++, "rect");
        b.AddAttribute(s++, "x", "2");
        b.AddAttribute(s++, "y", "15");
        b.AddAttribute(s++, "width", "20");
        b.AddAttribute(s++, "height", "4");
        b.AddAttribute(s++, "rx", "1");
        b.CloseElement();
    }
}
