// <auto-generated />
using Microsoft.AspNetCore.Components.Rendering;
using ShadBlazor.LucideIcon.Base;

namespace ShadBlazor.LucideIcon;

public sealed class LucideSquareSplitHorizontal : LucideIconBase
{
    protected override void RenderChildElements(RenderTreeBuilder b, int s)
    {
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M8 19H5c-1 0-2-1-2-2V7c0-1 1-2 2-2h3");
        b.CloseElement();
        b.OpenElement(s++, "path");
        b.AddAttribute(s++, "d", "M16 5h3c1 0 2 1 2 2v10c0 1-1 2-2 2h-3");
        b.CloseElement();
        b.OpenElement(s++, "line");
        b.AddAttribute(s++, "x1", "12");
        b.AddAttribute(s++, "x2", "12");
        b.AddAttribute(s++, "y1", "4");
        b.AddAttribute(s++, "y2", "20");
        b.CloseElement();
    }
}
